### ISSUE TITLE
electron app needs polish

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#1045]
![image](https://user-images.githubusercontent.com/73749/39548671-2e210b3a-4e10-11e8-9364-c2664f0138e5.png)

* need to suppress error messages at the bottom of the welcome screen
* session delete buttons missing
* "Previous sessions" needs styling
* change "Previous sessions" to "Saved sessions"
* don't mention that this is desktop mode, they know it's a desktop app
* make user session names more human readable, not long paths
* fix alignment and styling of "open *" buttons
* need to have a mechanism to delete unused sessions after a certain amount of time, so that heavy users don't have old sessions piling up

some of these might be regressions

**Comment by cmdcolin** [comment]
Agree with all these items :) I guess the error message thing is since the welcome page is sort of a modification of the error page. I could either suppress the error if it's just the 404 on that data dir, or I could try and redesign the welcome so it's a different setup. Not sure which is better. Agree with the other things though, the only regression is that the session delete button is missing probably just due to css
