### ISSUE TITLE
stopping at "installing node.js dependencies and building with webpack" when running setup.sh

### ISSUE THREAD

**Issue by billzt** [GMOD/jbrowse#1051]
I am running setup.sh, however it stops at `installing node.js dependencies and building with webpack ...` for more than an hour... and it did not finish.

How do I know the progress of it?

**Comment by cmdcolin** [comment]
I was thinking that perhaps adding --no-progress and --verbose to the npm/yarn steps in setup.sh might help to see exactly what is happening during the install.

```
-        npm install yarn
-        node_modules/.bin/yarn install
+        npm install yarn --no-progress --verbose
+        node_modules/.bin/yarn install --no-progress --verbose
```

Then you can tail -f setup.log and see if it is getting stuck.

Also, just a random note, but at least with running this on WSL on windows, it took a very long time because of antimalware scanning. I added an exclusion rule to the jbrowse data directory which significantly improved the runtime

**Comment by cmdcolin** [comment]
These files main.uncompressed.js are relics of the old jbrowse build system pre-webpack. Are you using a git clone from an older version? For easiest solution if you are using git clone I would just reclone a fresh copy since I cant tell you specifically which files to remove (or rm -rf plugins and git checkout plugins to just refresh that dir)

**Comment by billzt** [comment]
Yes. After I remove the plugin dir and copied a new one, it can now run properly.
I have also discoveedr the new problems: 
The new version of JBrowse strongly depends on the data cache. After I add/remove genome datasets, they can not change immediately. I must emptify the web browser cache and then they would work.

**Comment by cmdcolin** [comment]
I can't imagine why caching would be more of a problem, the clear cache thing is pretty common when doing changes to data directory contents. If it becomes a big issue feel free to open a new GitHub issue for it:)

I guess since the original issue is solved we can close for now though
