### ISSUE TITLE
Genome name truncated in top bar

### ISSUE THREAD

**Issue by srobb1** [GMOD/jbrowse#1059]
Just another small thing to note with 1.14.1-dev.

My genome names are truncated when they are displayed in the top menu bar.

![screen shot 2018-05-23 at 12 38 59 pm](https://user-images.githubusercontent.com/1072991/40444371-76b18e20-5e86-11e8-8aa6-70841abc9987.png)

![screen shot 2018-05-23 at 12 41 50 pm](https://user-images.githubusercontent.com/1072991/40444480-c06d6642-5e86-11e8-916f-b3d946406ba3.png)

Thanks,
Sofia

**Comment by rbuels** [comment]
@srobb1 this is a little bit of a tough thing design-wise, because the genome names could potentially be very long (your aren't, but some people's could be), so there has to be a limit to how wide the menu can be.  otherwise, if somebody had long names it would take up the whole top bar and squeeze out everything else.

I could look at making the maximum width of this configurable, do you think that would help?

**Comment by srobb1** [comment]
Yes! A configurable width would be great!
