### ISSUE TITLE
Dump data for all genome

### ISSUE THREAD

**Issue by yloemie** [GMOD/jbrowse#1090]
Hi,
I wanted to know if there is a simple way to get a gff for a track for the whole genome. Like the save track data option but for the whole genome.
My case is simple, I have lost one gff I have uploaded on the browser and I want to recover it, but in my case the genome I use is made of more than 1000 contigs.
Maybe a script in the bin folder (json-to-flatfile ?) should be very useful.

Thanks,

Best

**Comment by rbuels** [comment]
There is no such script right now. Did you load the original gff with flatfile-to-json.pl?

**Comment by cmdcolin** [comment]
I made a way to programmatically access the jbrowse data store in JavaScript which could be used to reconstitute the features somewhat.

See https://gist.github.com/cmdcolin/1bc8559c03bff9f9e353413a8d94c8ff

This in principle works better with jbrowse 1.12.5 or older because the newerr ones would require that code to be compiled with webpack. Basically you can just take this file though and save it as "export.html" and it'll get the data from all refseqs

There are some hardcoded paths but you can adjust those as needed. Also there is a note about empty contigs in the gist itself, if relevant

**Comment by rbuels** [comment]
Closing for now, reopen if further action is needed!

**Comment by yloemie** [comment]
Hi,

Yes I have loaded from a gff with flat-file-to-json.pl,

I will check your thread, many thanks.

Yann
