### ISSUE TITLE
refactor/rewrite/extend indexed-fasta stores

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#1152]
* add bgzip+fasta support as in #1138 
* pull all low-level parsing code out into node modules that support uncompressed and fai-indexed fasta files, and compressed and .gzi-indexed fasta files

from #1138:

The fasta+fai index is not compressed, might be nice to get the bgzip fasta + the gzi index
Barebones level of gzi index docs here http://www.htslib.org/doc/bgzip.html

**Comment by rbuels** [comment]
2 new node packages are coming out of this: [bgzf-filehandle](https://github.com/GMOD/bgzf-filehandle) and another called indexed-fasta that will use bgzf-filehandle (or regular filehandles).  bgzf-filehandle is pretty much done, indexed-fasta is the next thing to do on this.

**Comment by cmdcolin** [comment]
I have a simple little module now that implements unindexed FASTA, indexed FASTA, and bgzip compressed indexed FASTA https://github.com/cmdcolin/fasta-js

I'd like to get it set up with both browser+nodejs tests

Also I think one more task that would be good to do is: for unindexed fasta, it should actually stream the file and generate a FAI on the fly instead of reading entire file into memory.

**Comment by cmdcolin** [comment]
I adopted the twobit tests for indexedfasta so now they should have a similar API and test suite :)

New link https://github.com/GMOD/indexedfasta-js

**Comment by cmdcolin** [comment]
The branch has been merged :) Feel free to test and open up new issues if they arise
