### ISSUE TITLE
Add a "mailto" on a right click feature 

### ISSUE THREAD

**Issue by ThomasLet** [GMOD/jbrowse#1172]
Hello :)

I try to add a "mailto" on a specific try (I want to launch this event when a user right click on the feature).

I wrote this code but it's not working, I have no error in the debug mode of chrome, nothing happen when I click on "Order this BAC".

```
    {
               "iconClass" : "dijitIconMail",
               "label" : "Order this BAC !",
               "action": "Javascript callback",
               "content": "function(Name){var test = 'mailto:test@test.com:&subject:Order this track'+this.feature.get('name'); return test;}",
            }


```

This code is included in the "menuTemplate" part of my trackList.json.

I suppose that the JS function is not correct but I'm still looking to find why...

Many thanks for your help,

Regards,

Thomas

**Comment by cmdcolin** [comment]
I would use {name} to fill in a template like this

```
    {
               "iconClass" : "dijitIconMail",
               "label" : "Order this BAC !",
               "url" : "mailto:test@test.com?subject=Order this track {name}"
            }
```

I think if you wanted to use the javascript callback you'd have to have some way to click or redirect to the mailto link

**Comment by cmdcolin** [comment]
If there are any more questions let us know, I guess maybe close for now?

**Comment by thomas77** [comment]
Hi cmdcolin,

thank you for your help.

I tried your code but unfortunaly it doesnt work, when I click on the event it colors the jbrowse area in yellow, I dont know why...

**Comment by ThomasLet** [comment]
Ok using "action" : "newWindow" it works ! Thanks again !

**Comment by cmdcolin** [comment]
Glad that works for you. The reason you saw the area colored in yellow is that the menuTemplate configuration customizations in trackList.json has some weird behavior. The way it works is the customizations overwrite the existing menu items that the default right click menu has, but it can do this "incompletely", so therefore, your menu item basically incompletely overwrote the default "Highlight this gene" menu item but since the action wasn't overridden it reamined a highlight button.

This is sort of a weird workaround, but if you dont want to overwrite these menu items and instead append to the list of menu items, you can create "Dummy" menu items in your trackList.json config, for example


         "menuTemplate" : [
            {
               "label" : "View details"
            },
            {
               "label" : "Zoom this gene"
            },
            {
               "label" : "Highlight this gene"
            },
            {
               "iconClass" : "dijitIconMail",
               "label" : "Order this BAC !",
               "url" : "mailto:test@test.com?subject=Order this track {name}"
            }
         ],


This workaround is documented with a footnote here http://gmod.org/wiki/JBrowse_Configuration_Guide#Customizing_Right-click_Context_Menus but deserves a little more documentation probably
