### ISSUE TITLE
rewrite/refactor BAM store and BAI index support into node modules

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#1178]

**Comment by rbuels** [comment]
you're going to want to use `unzip` from `@gmod/bgzf-filehandle` for unzipping the BAM chunks, I think.  node zlib requires special options to properly unzip chunks that contain multiple bgzf blocks, and browserify-zlib doesn't work on them at all (https://github.com/devongovett/browserify-zlib/issues/34)

```js
const { unzip } = require('@gmod/bgzf-filehandle')
const unzipped = await unzip(chunkData)
```

**Comment by cmdcolin** [comment]
I have some progress on this on the https://github.com/GMOD/jbrowse/compare/dev...use_bamjs branch. Current concerns:

- It is currently slower than the default implementation due to a lot of decoding of bgzip blocks, I am wondering if I might be able to optimize this 
- It requires some work on making sure the BAM features themselves are decoded properly and have a nice "feature class" and API

Nevertheless, we can view BAM files, CIGAR strings, MD tags, sequence, etc in jbrowse with the bam-js module now

Picture of a track rendered with bam-js plus the performance logging showing a lot of decoding while scrolling around

![t1](https://user-images.githubusercontent.com/6511937/45784168-ca697e80-bc35-11e8-871c-386012235ed5.png)

**Comment by cmdcolin** [comment]
The speed issue is largely resolved after fixing caching layer in bam-js :)

**Comment by cmdcolin** [comment]
This is merged onto dev now. Please test it out with your favorite giant or weird BAM files!
