### ISSUE TITLE
If index file does not exist, error is confusing

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#1180]
If I am using the new remote file cache, then the error it gives if you are missing an index file is a bit confusing

It performs redispatching and then ends up with an error message that is not rendered properly

![bb](https://user-images.githubusercontent.com/6511937/44226187-6a2a7d00-a15d-11e8-8a70-0d0c5af35546.png)

**Comment by garrettjstevens** [comment]
@cmdcolin, so it looks like the problem is that `tenacious-fetch` (386813f5e9b0eeb8ec55cd3c80b24900351c0a09) doesn't act exactly like `fetch`. If it runs out of retries on one of the retry status codes (500, 404, 503), instead of just passing the response on it throws an error. Since there wasn't a failure callback, it just passed on the response promise unmodified. That's the weird `[object Response]` you saw. I just added a failure callback for the promise so that it actually throws an error instead of just passing on the response. This is what the error message looks like now:

![image](https://user-images.githubusercontent.com/22651474/44741481-32abc100-aacb-11e8-923d-3e6aeaf9cc16.png)

Does that work, or do we need something more?

**Comment by rbuels** [comment]
@garrettjstevens so tenaciousfetch just throws the response object into the rejection of the promise? that's weird.

**Comment by garrettjstevens** [comment]
@rbuels, yeah, I think that's what it's doing below, right? (I'm still new to the whole promise model, so I could be wrong). `fetch` will resolve the promise as long as there is some sort of status code, but `tenacious-fetch` rejects the promise when one of the status codes is in `retryStatus` (after retrying).

https://github.com/tiaanduplessis/tenacious-fetch/blob/bfec7dcdb1c9f8a49765742dd479e6f131d150f5/src/retrying-fetch.js#L21

**Comment by rbuels** [comment]
Yep, that’s what it does. :-P
