### ISSUE TITLE
Summary histograms for GFF3Tabix top level feature tracks

### ISSUE THREAD

**Issue by shihabdider** [GMOD/jbrowse#1201]
Hi,

Related to #935 

I'd like to create a summary histogram for a gff3 top level feature track. I understand that the storeclass requires a custom bigwig file to generate the histogram and bedtools genomecov is suggested in #935 to generate the bigwig file, but I'm having memory issues (even when splitting the genome file by chromosome) with bedtools. Is there an alternative?

Also, the flatfile-to-json.pl script can generate the bigwig automatically, perhaps this can be implemented in JS (since JBrowse is moving away from perl scripts)?

Best,
Shihab

@ihh @cmdcolin

**Comment by cmdcolin** [comment]
The alternative is available already and there is built in code to dynamically generate a histogram from the features themselves in GFF3Tabix. By default, it will try and estimate "when it is appropriate to display the histogram" depending on if the feature density on the screen is too high. If you are not seeing the histograms in your track, you can try and make maxFeatureScreenDensity=0.1 or a small fraction like this (default is 0.5) to force the histograms to show up even when feature density is sort of low. Note that the JBrowse 1.15.3 has extra code that helps with the GFF3Tabix histograms so recommend updating to the latest version as always :)

Even saying this, you might want pre-generated bigwig histograms since generating the histogram dynamically requires downloading a bunch of the GFF3 data and parsing it up front so it is a little bit resource intensive (especially if, for example, you are using topLevelFeatures as a filter, since that means it will download a bunch of data for unrelated features)

All this said, the memory issues and splitting up by chromosome are undesirable as ideally jbrowse should support GFF3Tabix files without too much fuss so if you have more information it would be good to know specific sample test data and stuff. Cross-ref https://github.com/GMOD/jbrowse/issues/1195

**Comment by shihabdider** [comment]
@cmdcolin 

Great to hear it's already implemented! However, when I set the "maxFeatureScreenDensity" to something tiny (0.01), the histogram still won't generate and the features will still hit the max height limit. 

[e.g](http://ec2-18-144-75-19.us-west-1.compute.amazonaws.com/?loc=chr1%3A80783715..172469635&tracks=DNA%2CHomo_sapiens.GRCh38.93_exon.gff3.gz&highlight=)

I am currently running version 1.15.0 of JBrowse. Is dynamic histogram generation for GFF3Tabix on a later version (1.15.3 as you mentioned)?

**Comment by cmdcolin** [comment]
I am getting a weird error from your instance "Error: too many length or distance symbol"

Is the file properly created with bgzip and tabix? If I download it and reindex it with bgzip and tabix it works fine locally

**Comment by shihabdider** [comment]
@cmdcolin 

Sorry about that I was doing some maintenance on the database. It should be working now. Interestingly, of the two tracks [here](http://ec2-18-144-75-19.us-west-1.compute.amazonaws.com/?loc=chr1%3A7575001..16970000&tracks=DNA%2CHomo_sapiens.GRCh38.93_exon.gff3.gz%2CHomo_sapiens.GRCh38.93.abinitio_exon.gff3.gz&highlight=) the histogram works for one but not the other. Even after I change the "maxFeatureScreenDensity".

**Comment by cmdcolin** [comment]
The reason you don't get histograms is because you are getting store statistics timeouts. If the statistics timeout it just defaults to displaying all features.


But, luckily, since version 1.15.2 the statistics calculation should happen fast and you will not get timeouts (I mentioned that this improvement happened in the last thread https://github.com/GMOD/jbrowse/issues/1179). So basically, I just recommend upgrading your jbrowse if you want histograms

**Comment by cmdcolin** [comment]
Close for now :)
