### ISSUE TITLE
ModSecurity CRS conflict

### ISSUE THREAD

**Issue by ClayBirkett** [GMOD/jbrowse#1216]
Using JBrowse 1.12.5 on linux apache machine. JBrowse is blocked by ModSecurity CRS 3.1 application firewall running on that machine. To fix the problem I disabled the check for "package.json" which it considers a "local file injection". https://www.owasp.org/index.php/Testing_for_Local_File_Inclusion. I also had to disable the check for file extension ".conf" when loading jbrowse.conf which it considers a restricted file extension. Maybe it could be renamed config.js

**Comment by cmdcolin** [comment]
I don't think there should be any actual security issue and there is some "legacy" aspect of simply referring to our files as .conf files that makes it difficult to change. You can safely delete package.json after running setup.sh and the config system is quite flexible and could refer to files named differently than jbrowse.conf and tracks.conf but I think disabling that check seems fine.

Thanks for reporting though :) I guess since you have a workaround we'lll close for now
