### ISSUE TITLE
Has the NeatCanvasFeatures plugin been broken in 1.16.0?

### ISSUE THREAD

**Issue by billzt** [GMOD/jbrowse#1294]
Both the demo (http://jbrowse.org) and my own instance has no NeatCanvasFeatures looking (intron hats and a gradient 'tubular' ).

I've tried to follow the https://github.com/GMOD/jbrowse/blob/master/plugins/NeatCanvasFeatures/README.md however with no results

**Comment by cmdcolin** [comment]
The NeatCanvasFeatures and NeatHTMLFeatures were changed into track types instead of being globally applied to all tracks. This change was introduced in 1.15.0. 

You can see on the volvox sample browser that the "CanvasFeatures - Protein-coding genes" has this enabled. You also have to manually set "gradient": true in your config to get this look.

**Comment by cmdcolin** [comment]
Also those docs were slightly incorrect, fixed in https://github.com/GMOD/jbrowse/commit/7e66f38e724afd0ed81d239c9d4138101f2f14ff

**Comment by billzt** [comment]
resolved, thanks!
