### ISSUE TITLE
prepare-refseqs.pl

### ISSUE THREAD

**Issue by mictadlo** [GMOD/jbrowse#1324]
Hi,

1. Should I use `prepare-refseqs.pl --gff` after I used `flatfile-to-json.pl --gff`? 
2. Does `prepare-refseqs.pl --gff` support to use more than one gff3 file?
3. Do I use `prepare-refseqs.pl --twobit` only if I want to use BLAT or does it has any other purpose? 
4. How do I make the input files for prepare-refseqs's `--conf`, `--sizes` and `--gff-sizes`?

Thank you in advance,

Michal

**Comment by cmdcolin** [comment]
This is sort of a weird question because it seems to misunderstand what prepare-refseqs.pl does. The main thing it does is it loads a reference sequence track into jbrowse, it creates the sequence track and creates the dropdown menu to select which refseq you are browsing. It does not have any interaction with BLAT, that is an apollo specific feature not a jbrowse feature. Using prepare-refseqs with --gff is a rare circumstance where your reference sequence is embedded in your gff, not too commin. Similarly running prepare-refseqs with the options for --conf and --sizes and --gff-sizes are similarly rare and you would probably know if you need this functionality.

Running prepare-refseqs only needs to be done once, and it only needs to be run for the reference genome that you are using.

Just use `prepare-refseqs.pl --fasta yourgenome.fasta` optionally with the --out parameter as needed and that's it :)

**Comment by mictadlo** [comment]
Thank you. Should I use `--indexed_fasta` after  `--fasta`?

**Comment by cmdcolin** [comment]
No, as I said it only needs to be run once. I would just use --fasta

**Comment by mictadlo** [comment]
Thank you.
