### ISSUE TITLE
Troubles with vcf tracks when ugrading JBrowse version

### ISSUE THREAD

**Issue by ThomasLet** [GMOD/jbrowse#1332]
Hello,

I upgraded my JBrowse version from 1.11.5 to 1.16.3 and I get an error with all my vcf tracks:

![jb](https://user-images.githubusercontent.com/5164756/54202966-7e571280-44d1-11e9-996d-ad1d12d4c1af.png)

and this is what I get in the console log :
![jb2](https://user-images.githubusercontent.com/5164756/54203017-9d55a480-44d1-11e9-8592-2086308336ae.png)

Any ideas ?

I'm using firefox 65.0.1 (64-bit) and chrome  71.0.3578.98 (same error in both browsers).

Thank you for your help,

Regards,

Thomas

**Comment by garrettjstevens** [comment]
Hello,
If you are able to share your track configs and perhaps the track data, that would help a lot in figuring out what's going on. Thanks.

**Comment by ThomasLet** [comment]
Sorry I forgot it ! Here it is:

> 

      {
         "key" : "Berkut",
         "tbiUrlTemplate" : "vcf_files/Berkut.vcf.gz.tbi",
         "storeClass" : "JBrowse/Store/SeqFeature/VCFTabix",
         "urlTemplate" : "vcf_files/Berkut.vcf.gz",
         "maxHeight" : "1000",
         "label" : "Variations",
         "category" : "Varietal SNPs / Hexaploid",
         "type" : "JBrowse/View/Track/HTMLVariants"
      },

>

**Comment by cmdcolin** [comment]
The source of the error is that you are using a plain tabix index on a chromosome that is longer than 2^29=536870912

594102056=your chromosome

Previous jbrowse versions allowed tabix files like this but they are technically invalid. And the source of that issue is that older versions of tabix generate invalid tabix files. If you try to recreate your index with a recent version of tabix it will say "[E::hts_idx_push] Region 536930580..536930581 cannot be stored in a tbi index. Try using a csi index with min_shift = 14, n_lvls >= 6".

Therefore should use tabix -C -p vcf yourfile.vcf.gz

This PR #1330 will throw a better error message for this issue but needs a new jbrowse release

**Comment by ThomasLet** [comment]
Ok thank you @cmdcolin  !

**Comment by cmdcolin** [comment]
Sure thing. You'll want to manually specify csiUrlTemplate=yourfile.vcf.gz.csi also in your new configs
