### ISSUE TITLE
change the color of the lines

### ISSUE THREAD

**Issue by julianabc29** [GMOD/jbrowse#1350]
Hello
I am using JBrowse, and I uploaded this gff file

![gff](https://user-images.githubusercontent.com/41842945/55561289-844aa880-56b7-11e9-9ff2-b058076da825.png)

bin/flatfile-to-json.pl --trackType CanvasFeatures --gff test.gff --trackLabel NAMETRACK
with these results...

![GENE](https://user-images.githubusercontent.com/41842945/55561651-28345400-56b8-11e9-9c45-9d9a1314cf67.png)

I want to ask, How can I change the color of the gene, RNAm and CDS ?
I see these three structures with the same color.
Thanks

**Comment by cmdcolin** [comment]
@julianabc29 this is an interesting question but actually what you are seeing is the result of jbrowse not reconstructing the feature hierarchy properly.

The cause is that there is a space between "; Parent=blahblah"

If you make it ";Parent=blahblah" with no spaces it will make all those one feature

**Comment by julianabc29** [comment]
@cmdcolin Thanks for your help but can I change the color to make a difference between gene, RNA and CDS?

**Comment by cmdcolin** [comment]
yes, see the dynamic coloring example here

http://jbrowse.org/docs/faq.html#how-do-i-customize-feature-colors-with-canvasfeatures

you can use feature.get('type') instead of feature.get('score') to get the type of the feature in your callback and then return different colors
