### ISSUE TITLE
Can I embed ncbi blast to JBrowse

### ISSUE THREAD

**Issue by anajulia95** [GMOD/jbrowse#1362]
Can I embed the tool blast to JBROWSE?
I have a specific sequence and I a need Blast to make an aligment between my sequences and my genes in JBROWSE. Is it possible?

**Comment by cmdcolin** [comment]
Some options

* you can run BLAST on the command line or similar, pre-process results, and then upload it as a track
* you can use a BLAST server like SequenceServer and integrate it with JBrowse https://jbrowse.org/docs/faq.html#how-can-i-link-blast-results-to-jbrowse
* you can use a packaged solution like JBlast/JBConnect @enuggetry  https://jblast.readthedocs.io/en/latest/

Note that JBrowse is a "client side app" and does not feature any server side functionality that would allow it to run programs like BLAST dynamically, which is why there is not any pre-built solution directly inside JBrowse

**Comment by cmdcolin** [comment]
I have provided an overview of methods to integrate blast above. If you have any questions feel free to follow up.
