### ISSUE TITLE
Flask server and user-uploaded data

### ISSUE THREAD

**Issue by MarkleLab** [GMOD/jbrowse#1386]
Basic Information:
- JBrowse version: JBrowse-1.16.5
- Web browser being used: Chrome
- Operating system if relevant: macOS High Sierra
- If it is setup related, setup.log. Attached.
[setup.log](https://github.com/GMOD/jbrowse/files/3311991/setup.log)

Hi,

I'm trying to setup JBrowse within my Flask server, and I'm having a bit of trouble. 

I am able to embed it inside my webpage. I placed the entire directory jbrowse into the static folder of my site structure. And after running setup.sh, I get the following embedded in my webpage. I am able to load and play around with the Volvox dataset. 

<img width="1272" alt="Screen Shot 2019-06-20 at 4 27 06 PM" src="https://user-images.githubusercontent.com/43764863/59879266-484ee780-9378-11e9-9e3d-68dfda10bee4.png">

My aim is to be able to load and visualize BAM/BAI files for human patients located on a file server. I have CORS enabled in my flask config file. How can I do this with JBrowse? 

1. Is loading user-uploaded data even doable with a Flask server? All your documentation is with Apache and nginx, so I'm curious. JBrowse looks amazing and it'd be great if there was support or Flask.
2. I think I might need a reference for hg19/38. Is this commented out somewhere in the jbrowse code, or do I have to retrieve this myself? 

Thanks,
MarkleLab

**Comment by cmdcolin** [comment]
Hi there

I'm glad you're interested in JBrowse. 

It seems to me that you probably just want JBrowse to access those files that are on your file server already, not to provide an upload interface. Is that correct? Is your file server already running an http server? JBrowse is perfectly happy with accessing files from a remote file server if that remote file server has CORS enabled on it. How you configure that can follow different paths, you could preload all the files into your tracklist, or you could tell users to copy and paste the URL of the files into the Track->Open track dialog box, or something else even.


Also, JBrowse does not provide a pre-defined reference for human. Generally you just download a FASTA file for whatever you are working with and run `bin/prepare-refseqs.pl --fasta yourfile.fa` and then it replaces that screen you are seeing (The congratulations...your jbrowse is on the web) and just goes straight to the genome browser. There are alternatives, for example you can create a directory named "data" and a file called "tracks.conf" in the data directory with these contents and it just remotely loads a indexed fasta file instead of you having to download and run that script

```
[GENERAL]
refSeqs=https://s3.amazonaws.com/1000genomes/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa.fai
[tracks.refseqs]
urlTemplate=https://s3.amazonaws.com/1000genomes/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa
```

**Comment by MarkleLab** [comment]
Hey, thanks for getting back! 

Actually, I would very much like to provide an upload interface as well. I don't think preloading tracks or users copying/pasting is the direction we want to go in. Is this possible with JBrowse? Users selecting files on the fly from the select track menu? 

As for the server, I'm not a 100% sure if the file server is running an HTTP server. Its an SMB share? 

And you raise a good point. I've enabled CORS in the local server I'm constructing, but I'm not sure if the file server supports CORS from its side.

And thanks! I understand the part about the reference FASTA. Thanks for the clarification on that! 👍 

Thanks,
MarkleLab

**Comment by cmdcolin** [comment]
Glad to help, I just wanted to lay out the option of how you could possibly use jbrowse to access the remote files without a file upload but that requires that it's already on an HTTP server

Anyways, the reason why this often involves "build your own" solutions is that JBrowse is a "client side app" which means it actually does not run any server side code (and that similarly affects how it is able to access remote resources, it requires remote resources to reside on HTTP).

The easiest thing to do would be to provide a completely separate file upload script, and then generate some URLs for your uploaded files, and instruct users to load it via the Track->Open track menu

You  could also dynamically append to a trackList.json file or tracks.conf file when the file upload is done to make it more automatic. If you need sessions for different users that is again more customization but one large tracklist is fine, then appending to the tracklist should be easy

**Comment by MarkleLab** [comment]
Thanks a lot @cmdcolin! I understand that JBrowse is a client side app and that there's no out-of-the-box way for this to happen. I will have to write some scripts to configure this. 

Your comments are extremely helpful, though. I will prepare a custom script for file selection, generate URLs on the fly, and then try to append them to the trackList.json file (I found it in jbrowse/data/seq/ 👍)! And we probably won't require sessions, but I might write a script to clear up the appends, leaving the reference track untouched.  

Thanks again for your guidance. This was very helpful! I'm very excited to set this up. Should be a fun afternoon. (I'm going to close the issue. Will let you know if I have any follow up questions)
