### ISSUE TITLE
Prerequisites/dependencies need updating in Installation instructions

### ISSUE THREAD

**Issue by mjy** [GMOD/jbrowse#1432]
# Pre-requisites

* When I attempt to install JBrowse on a pristine install of Ubuntu Server 18.04.3 then the prequisites listed in the (install instructions)[https://jbrowse.org/en/developers.html] do not match the response I get from `./install.sh`

* Running on master branch

* "As a first troubleshooting step, make sure development libraries and header files for GD, Zlib, and libpng are installed and try again."  This is too vague, we had to decipher what GD, etc. libs are referenced in context of `apt`.  We shotgun install libraries that seem to match, but are unsure preqs are there.

* Error messages on `./install.sh` indicate a failed run, when in fact they seem to pass

See also https://github.com/GMOD/jbrowse/issues/1313

**Comment by cmdcolin** [comment]
Can you attach a setup.log file please?

**Comment by mjy** [comment]
I think the real issue is that the Quick-Start guide served by the app (`docs/tutorial/` is not aligned with  https://github.com/GMOD/jbrowse/wiki/JBrowse_Configuration_Guide.   If I follow the latter then I expect I'll have no problem.

**Comment by cmdcolin** [comment]
I know it's a little crazy that the documentation is in many different places.  Inspecting the setup.log is basically helpful and I'm happy to try to help with it if you post it. It's hard to provide specific recommendations without it. I assume you are referring to setup.sh instead of install.sh also is that correct

**Comment by mjy** [comment]
Thanks for the offer.  Sorry for install/setup confusion, you're right about that.

However, the issue really was opened to help clarify the documention (we got things working, there are enough breadcrumbs, the log etc. to figure that out).  It should be as easy as just wiping the doc there and pointing to the canonical version, i.e. the wiki?

**Comment by cmdcolin** [comment]
@mjy The most up to date docs are currently hosted at jbrowse.org but that is fairly recent change (within the last year). Here is a quick install guide for example https://jbrowse.org/docs/installation.html


 it seems like people still find our docs frequently through the wiki in one way or another so it's sort of difficult to figure out how to "fix the docs". I am not a big fan of deleting all the wiki content because that can break links...ideas welcome though

**Comment by mjy** [comment]
@cmdcolin I'm slammed for the next couple of weeks, but will be implementing JBROWSE into a genomics front end in the following months.  Will try and get the project more concrete feedback, or PRs during that process.

**Comment by cmdcolin** [comment]
I guess close for now. If you have recommendations let us know
