### ISSUE TITLE
Ability to globaly enable or disable sequence translation to protein in reference sequence track

### ISSUE THREAD

**Issue by elhossary** [GMOD/jbrowse#1466]
The problem:
In each time I open a new JBrowse link I have to manually uncheck "Show translation" checkbox to minimize the reference sequence track hight.

I wish that you add the ability to disable it globaly in JBrowes just like the enabling or disabling "show_tracklist"
I have searched to find if it's possible to that but I could not.
The reason for this is that I need to match some certain sequences at spcific positions by my eyes, while having the translation enabled will make it distracting to do so.

Thanks

**Comment by cmdcolin** [comment]
There is a configuration on the dialog box to fully disable this on all reload is called showTranslation: false, it can be added to the trackList.json

We stopped short of fully persisting all custom configuration changes such as this across reloads because we found it could be confusing, the PR for that was here https://github.com/GMOD/jbrowse/pull/1272

If it is needed to persist this specific change across refreshes, we would welcome a PR to do that!

**Comment by elhossary** [comment]
Many Thanks, I did it

**Comment by cmdcolin** [comment]
Super, glad that
