### ISSUE TITLE
Colour VCF track by FILTER category

### ISSUE THREAD

**Issue by lyijin** [GMOD/jbrowse#1528]
First of all, thanks for including an option to hide variants by FILTER category (by right-clicking on the track label, for those who aren't aware).

However, I'd like to additionally colour the SNV by FILTER category. After reading the docs, seeing the warning about using hooks -> modify for VCF files, and checking volvox's tracks.conf `variantIsHeterozygous` function, I came up with this for my tracks.conf file but the hooks -> modify doesn't seem to work the way I thought it would.

In my test config below, I expect PASS to be coloured blue, not-PASS to be red.

```
      {
         "storeClass" : "JBrowse/Store/SeqFeature/VCFTabix",
         "urlTemplate" : "../vcf_tracks/lalala.vcf.gz",
         "label" : "testsnps",
         "key" : "Test SNPs",
         "category" : "SNPs",
         "type" : "JBrowse/View/Track/HTMLVariants",
         "hooks": {
            "modify": "function(track, feature, div) {div.style.backgroundColor = feature.get('filter') == 'PASS' ? 'blue' : 'red'; }"
         }
      },
```

From what I can tell from https://jbrowse.org/docs/faq.html, the `feature.get` command seem to be tailored towards GFF3 fields. I'm not sure whether `feature.get` can get the FILTER field from VCF. Can it?

I'm terrible with JS so apologies if I've made a blindingly obvious error (triple-equals instead of double?). Thanks!

PS if you don't mind teaching me how to fish, is it possible for me to use the browser console to inspect the values/methods in `feature.get`? I think it'd be easier to troubleshoot my own problem had I known what kind of object I'm dealing with.

**Comment by cmdcolin** [comment]
A value returned from feature.get('filter') is actually an object that looks like this

```
{
  meta: {...some meta information about what filters exist in the vcf...}
  values: ["PASS"],
};
```

So you might want

```
div.style.backgroundColor = feature.get('filter').values.some(x => x==='PASS') ? 'blue':'red'
```

Kind of complicated, but working with VCF format is hard in general. Many of the values in a VCF file can actually be an array of values e.g. these there can be multuiple filters in a record, that is why we check like the above. Many of the INFO fields are also arrays. JBrowse just makes everything an array for vcf basically even if it contains one value to force the developer to consider that :)

**Comment by cmdcolin** [comment]
Also as far as converying a better understanding of the feature.get concepts, the basic idea is that we have this "feature" interface that bam reads, genes, gene subfeatures, etc conform to

That can be a SimpleFeature or it can be, as in VCF, a VCF Feature https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/Model/VCFFeature.js or in the CRAM and BAM cases they are called BamSlightlyLazyFeature https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/Store/SeqFeature/BAM.js

The function of these "lazy features" are to delay loading certain attributes until a user requests them, because deserializing the whole BAM record can take more time than partially deserializing it https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/Store/SeqFeature/BAM.js (same thing with VCF, for it's potentially long per-sample genotype column set)

**Comment by lyijin** [comment]
Thanks for the pointers! Tested what you wrote and it worked perfectly, and based on that, managed to hack something slightly more complicated to generate three colours for three FILTER types.

I'll go ahead and close this to mark this as resolved. Cheers again.
