### ISSUE TITLE
Some browser can not display the bam file

### ISSUE THREAD

**Issue by Trandamere** [GMOD/jbrowse#1542]
Hi:
The BAM file cannot be displayed in part of the browser．
![1](https://user-images.githubusercontent.com/24996924/91874116-65858280-ecac-11ea-9278-dd10d7772285.png)
Bam files can be displayed in GoogleBrowser, but not in Microsoft Browser.How can I avoid it．
I see that your presentation can be viewed in any browser．

**Comment by cmdcolin** [comment]
What server are you using? You should give status 206 for responses to range requests

**Comment by Trandamere** [comment]
centos 7.6

**Comment by Trandamere** [comment]
nginx

**Comment by cmdcolin** [comment]
Can you post a link to the live instance by chance? Can send me an email if it is helpful

**Comment by Trandamere** [comment]
http://123.56.75.179/HTML

**Comment by cmdcolin** [comment]
I believe you have to disable mime_magic on your server. This is a common issue on CentOS +Apache for us unfortunately

see
http://gmod.org/wiki/JBrowse_Configuration_Guide#Apache_Configuration_Note



(the response from the network indicates the server is apache not nginx from what I can tell)

The reason it works on chrome is that chrome has some fancy logic that smooths over this issue

**Comment by Trandamere** [comment]
thanks

**Comment by Trandamere** [comment]
Hi:
I added parameters to the configuration file, but it didn't work
```
    AddType application/x-compress .Z
    AddType application/x-gzip .gz .tgz
    AddType application/octet-stream .bam .bami .bai
```

![1](https://user-images.githubusercontent.com/24996924/93020117-06116600-f60e-11ea-8015-accb731efe8c.png)
FireFox browser

**Comment by cmdcolin** [comment]
What the issue boils down to is your server is sending this header in response to a BAM range request

Content-Encoding: gzip

![Screenshot from 2020-09-13 13-33-11](https://user-images.githubusercontent.com/6511937/93024725-67ade200-f5c6-11ea-8efc-33965520cd78.png)

This confuses jbrowse and cannot be handled because the browser unzips the BAM content as a gzip, whereas jbrowse is normally in charge of unzipping

I would suggest to disable mime_magic module entirely. If that is not possible I can't really guide the particular set of AddType that would help

You can look in the jbrowse mailing list archive for more details (gmod-ajax@lists.sourceforge.net) or github issues but I don't know what would help

This is really more of a server side issue than a jbrowse issue unfortunately :{

**Comment by cmdcolin** [comment]
To be clear, requests for a BAM file should *not* have Content-Encoding: gzip headers on them

**Comment by cmdcolin** [comment]
maybe close for now...known issue with server side config so sort of outside jbrowse scope
