### ISSUE TITLE
CRAM support

### ISSUE THREAD

**Issue by keiranmraine** [GMOD/jbrowse#546]
Hi,

We are being actively 'encouraged' to migrate to using CRAM instead of BAM for read storage and at present none of the popular genome browsers (e.g. Biodaliance, GBrowse, IGV, JBrowse) list it as a supported format (IGV indicates it will when Picard does) on their pages yet.

As we already use JBrowse we would be very happy to see support for this.

CRAM index files are also compressed so will be faster to transfer.

I noticed there wasn't a ticket for this so thought it was worth raising.

Regards,
Keiran

P.S. I can provide test files and test if needed.

**Comment by scottcain** [comment]
Hi @keiranmraine Do you happen to know if anybody has written a js library to support pulling CRAM regions?  If something like that exists, pulling it into JBrowse would probably not be too hard (written as someone who wouldn't be doing the work :-)

**Comment by cmdcolin** [comment]
Maybe use emscripten to compile htslib to javascript?

**Comment by keiranmraine** [comment]
Hi Scott,

The only person I can think of who may have started this would be Thomas Down the lead on Biodalliance (who I believe shared the BAM code with Robert)

http://www.biodalliance.org/

Keiran Raine
Principal Bioinformatician
Cancer Genome Project
Wellcome Trust Sanger Institute

kr2@sanger.ac.uk
Tel:+44 (0)1223 834244 Ext: 7703
Office: H104

**Comment by keiranmraine** [comment]
If any progress is made please consider me a very enthusiastic tester.

**Comment by selewis** [comment]
Not so far. But personally I'd like to put this very high on the list of
new feature priorities.

We're going to need it yesterday.

-S

On Tue, Jun 23, 2015 at 12:51 PM, Keiran Raine <notifications@github.com>
wrote:

> If any progress is made please consider me a very enthusiastic tester.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GMOD/jbrowse/issues/546#issuecomment-114622622>.
>



-- 
In the long history of humankind (& animal-kind too) those who learned to
collaborate & improvise most effectively have prevailed - Charles Darwin

**Comment by ihh** [comment]
I guess we could try the emscripten route as Colin suggests. zlib is the only htslib dependency and it has been successfully compiled into js with emscripten.

**Comment by cmdcolin** [comment]
Here is a guide for that  https://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html

It is a little tricky but it does have some standard ways of building with "emconfigure ./configure" and "emmake make". 

Then the tricky part is that you just call "emcc libhts.a" or something similar at the end, and this generates the javascript output (however, the javascript that this is creating for me so far has no htslib stuff in it).

**Comment by cmdcolin** [comment]
I wanted to add more interest in getting CRAM support.

We are experiencing some problems with some very big BAM files that we have (these are ones that are upwards of about 30GB). With these huge files, the tracks simply do not load 90% of the time. I don't know exactly where the bottleneck is, but this happens on standard apache servers, up to date nginx, and webapollo servlets, so it's not even really specific to the server. And, the reason it seems to fail on the client side is due to request timeouts.


Here are the statistics for our files here


    BAM files
    13G
    19G
    21G
    22G
    20G
    35G * +
    35G * +
    42G +


    * two different 35GB bam files
    + indicates that track fails to load probably more than 50% of the time although sometimes it does load. other tracks almost never fail



If we had cram, the files might be a bit smaller at least :)

**Comment by selewis** [comment]
CRAM is high on our list. We have to keep up with the times - and clearly
for very practical reasons.

How much (conservatively/realistically) effort do you think this might take?

**Comment by cmdcolin** [comment]
I'd say in the best case, it would be like one-to-two months of futzing around in emscripten. I would rather go that route rather than reimplementing the library at least given the other constraints we have. It might even be worth asking the developers of htslib about whether they have considered this

**Comment by keiranmraine** [comment]
@cmdcolin we regularly use BAMs in excess of 100GB (human, 30x+) and we don't see timeouts.  The main bottleneck we see is index retrieval as these can get into the 25MB+ range quite quickly.

One thing one of our developers noticed was that our proxy may be hiding some of the lag as when active all requests were actioned in parallel but when left to the browser alone only 4(?) we triggered at a time.  @mcast, can you chime in here as I'm fuzzy on the detail and may have this wrong.

**Comment by mcast** [comment]
On Tue, Jul 14, 2015 at 12:30:55AM -0700, Keiran Raine wrote:

> One thing one of our developers noticed was that our proxy may be
> hiding some of the lag as when active all requests were actioned in
> parallel but when left to the browser alone only 4(?) we triggered
> at a time.  @mcast, can you chime in here as I'm fuzzy on the detail
> and may have this wrong.

What I initially believed I observed, using Firefox's developer tools,
was

Firefox (approx v.32) limits the number of connections to each server
to some small number, but is otherwise happy to make many simultaneous
fetches.[1]

When configured to use a proxy, Firefox seems to delegate all(?) of
this stampede-prevention to the proxy, and issues many requests at
once.  Our local Squid is more eager to fetch many streams at once,
and I thought I had seen it open 30 parallel connections to local
webservers.

This is the origin of my expectation that using a proxy may increase
performance for large numbers of fetches from one HTTP server.


Then I saw the developer tools claiming that over 100 connections were
launched simultaneously, and returning simultaneously; but actually
the view on screen was not keeping up with the timeline.

I stopped trusting it as a diagnosis tool for this kind of
information, and I think Chromium's similar tool may be more reliable.

What I haven't done is objective comparisons of these timelines as
seen from the HTTP server - I lack a good tool for visualising the
request/response objects on a scrolly zoomy timeline.

-- 
Matthew

[1] This is the reason for (e.g.) the {s} placeholder in openstreetmap
tile server URLs,
  https://en.wikipedia.org/wiki/Leaflet_%28software%29#Use

so the client may provide {s} from ("a", "b", "c") to get three sets
of streams of traffic going.


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by cmdcolin** [comment]
Thanks for the detailed response. This is somewhat analogous to what i've seen with the parallel connections being launche...and that these are hard to debug. They are launched after the bai file download but they are all returning timeouts. It is interesting to see that you have gotten 100gb files to work. I might try and debug some more things to see if it's possible to fix my case

**Comment by cmdcolin** [comment]
<img width="644" alt="y1" src="https://cloud.githubusercontent.com/assets/6511937/8676817/49ec8d38-2a11-11e5-91b7-68a8e0e646ca.png">

Example of the chrome network tab. It is similar on firefox. It is sort of interesting because you can see the .bam.bai finishes (almost 7mb) and then two bam chunks finish, but then the remaining 13 are unfinished. This same thing happens in firefox, with the same number of requests, and the two pieces that finish.

Might need to check on the server side why that is happening.

**Comment by mcast** [comment]
On Tue, Jul 14, 2015 at 08:15:16AM -0700, Colin Diesh wrote:

> [ parallel connections ] launched after the bai file download but
> they are all returning timeouts. It is interesting to see that you
> have gotten 100gb files to work. [...]

For production we have nginx with an unremarkable configuration.


For some testing I also used Starman plus
 https://github.com/mcast/plack-middlewares-jbrowse

to implement the necessary subset of 206 Partial Content.  This may
prove easier to instrument?  It is not a polished bit of code though.

-- 
Matthew


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by cmdcolin** [comment]
@mcast super big thank you on your comments. I think it ended up that our problems were due to just a weird BAM file, perhaps it was made with a strange samtools version.

**Comment by mcast** [comment]
:sunglasses:
So...  error on client side, not reported in a meaningful way, breaking the fetcher?

**Comment by cmdcolin** [comment]
@mcast it was actually a really strange bug. I just kind of gave up after awhile because there weren't any clear symptoms other than that certain Content-Range requests would never complete and timed out eventually. No errors would be produced besides that. 

My speculation about the BAM file was sort of random but I realigned everything and created a new BAM file and it worked fine (and it was even larger than the original in the realignment, so the size issue that I thought was causing problems didn't seem to be a problem anymore)

**Comment by cmdcolin** [comment]
Anyways, I did want to post some updates on the "cram" support too, because I found a minute to test out some more emscripten compilation. My previous comment mentioned that the javascript files were lacking the htslib code, but I think that's because it would fairly aggressively just prune unused content

I did get it to compile with htslib outputs in the javascript but it remains to be seen if it can work :) If interested I can paste the procedure here too. It involves a couple tweaks but not to any source code so far, just makefiles

**Comment by keiranmraine** [comment]
We're starting to get poked with pointy sticks regarding switching to CRAM, is there any update on this?

I have a suggestion for a half-way house but I would need some assistance modifying the adaptor as it's not my expertise.

Basically my thought was we could put a light weight CGI server on the same host as the JBrowse system.  The JBrowse adaptor would be mostly the existing BAM one, except it would pass the requested coordinate range in the request instead of the byte range and expect to receive a compressed BAM steam as before, e.g.

```
# default compression
% time bash -c "curl -sS 'http://localhost:8080/test.cgi?loc=2:1..5000000;cram=test;zc=0' | pv | (samtools view -c - > tmp)"; echo -n 'Reads: '; cat tmp
3.31MiB 0:00:01 [2.84MiB/s] [ <=> ]

real	0m1.172s
user	0m0.090s
sys	0m0.040s
Reads: 68359

# fast compression
% time bash -c "curl -sS 'http://localhost:8080/test.cgi?loc=2:1..5000000;cram=test;zc=1' | pv | (samtools view -c - > tmp)"; echo -n 'Reads: '; cat tmp
 4.2MiB 0:00:00 [9.34MiB/s] [ <=> ]

real	0m0.458s
user	0m0.099s
sys	0m0.056s
Reads: 68359                             
```

* loc = genomic range in for chr:start..stop or chr:start-stop
* zc = compression level of returned BAM stream, 1=fast, 0/unset=default
* cram = dataset identifier

`zc` is available as setting this will reduce CPU load on the server, but it will increase I/O

My proof of concept is attached, I was just using [HTTPi](http://www.floodgap.com/httpi/) for the server.

```
#!/usr/bin/perl
use strict;
use CGI;

my $ok = '200 OK';
my $bad = '400 Bad Request';
my $page_state = $ok;

my $param_arr = chk_params(CGI->new);

print "HTTP/1.1 $page_state\n" if($ENV{SERVER_SOFTWARE} =~ m/^HTTPi/);
if($page_state eq $ok) {
  print "Content-Type: application/x-gzip\n\n";
  $|++;
  open(my $pipe, '-|', cram_to_bam($param_arr)) || die $!;
  while(<$pipe>) { print $_; }
  close $pipe || die $!;
}
else {
  print <<"END_MESSAGE";
Content-Type: text/html\n\n
<html>
  <head>
    <title>$bad</title>
  </head>
  <body>
    <h1>$bad</h1>
    <p>Expected params not found in request</p>
    <ul>
      <li>loc = genomic range in for chr:start..stop or chr:start-stop</li>
      <li>zc = compression level of returned BAM stream, 1=fast, 0/unset=default</li>
      <li>cram = dataset identifier</li>
    </ul>
  </body>
</html>
END_MESSAGE
}

sub chk_params {
  my $q = shift;
  my @req_params;
  push @req_params, 'genome.fa';
  push @req_params, $q->param('zc') =~m/^[1]$/ ? '-'.$q->param('zc') : q{};
  my $cram = $q->param('cram');
  push @req_params, $cram if($cram && $cram =~ m/[^$;@!*`()]/);
  my $range = $q->param('loc');
  if(defined $range) {
    $range =~ s/[.]{2}/-/;
    push @req_params, $range;
  }
  $page_state = $bad unless(@req_params == 4);
  return \@req_params;
}

sub cram_to_bam {
  return sprintf 'samtools view -b -T /var/tmp/%s %s /var/tmp/%s.cram %s', @{ $_[0] };
}

1;
```

**Comment by cmdcolin** [comment]
Hi @keiranmraine. That looks interesting but it would probably still need some extra work...probably can't just be used as a drop-in solution. A custom storeClass that does not perform range requests would probably need to be made 

I still am hopeful for the client side CRAM solution so that such a conversion of cram->bam on the fly is not necessary!

**Comment by keiranmraine** [comment]
Hi @cmdcolin GA4GH are working heavily on a new streaming API for sequence reads.  The idea is that the server side format is irrelevant and you can request SAM/BAM/CRAM at the client and receive the stream for the coordinate range requested.

The specification is here: https://samtools.github.io/hts-specs/htsget.html

I'm following up to see if there's a public implementation (or code you can run a test server with).

**Comment by keiranmraine** [comment]
Current test servers and interoperability matrix:

https://docs.google.com/spreadsheets/d/1AVe9febX0uwK44JBiyjPQYSv8cDePN4gW7NKsJA9HeQ/edit#gid=609687702

**Comment by nathandunn** [comment]
https://samtools.github.io/hts-specs/CRAMv3.pdf

https://github.com/samtools/htsjdk/blob/master/src/main/java/htsjdk/samtools/cram/encoding/reader/DataReaderFactory.java

**Comment by rbuels** [comment]
Some CRAM from rice: http://trackhubregistry.org/search/view_trackhub/AVrIY24vpL2YcDCmVC0g

**Comment by keiranmraine** [comment]
If useful human 21, cram with embedded ref: ftp://ngs.sanger.ac.uk/production/cancer/dockstore/cgpmap/insilico_21.cram

**Comment by nathandunn** [comment]
👍
