### ISSUE TITLE
Add ability for generate-names.pl to load included tracks.conf files

### ISSUE THREAD

**Issue by carrere** [GMOD/jbrowse#551]
Bonjour,

We are using  the "include" keyword in our tracks.conf to manage our tracks.
So we have one tracks.conf file with refSeq and GFF3 annotation and for example one myHits-tracks.conf file containing GMAP hits 

   include += ./myHits-tracks.conf

When I try to generate names for these data, only tracks from  tracks.conf are taken into account.
This behaviour come from GenomeDB.pm module (called in the sub "run" of IndexNames.pm):

``` perl
sub trackList {
    my ( $self ) = @_;
    my $json_tracks = $self->{rootStore}->get( 'trackList.json', { tracks => [] } )->{tracks};
    my $conf_tracks = $self->_read_text_conf( 'tracks.conf' )->{tracks} || [];
    return [ @$json_tracks, @$conf_tracks ];
}
```

included conf files are then ignored  and autocompletion is not available for these tracks.

**Comment by cmdcolin** [comment]
Good catch. patches welcome :)

**Comment by rdhayes** [comment]
Something to point out quickly is that generate-names.pl is only strictly
necessary for tracks that contain data that you wish to have searchable in
JBrowse by feature name/alias. I routinely do not index all tracks.

This one might be not that simple. The perl scripts for data generation
don't have access to the JBrowse installation main config where additional
include file names are specified (jbrowse.conf), as far as I know.

Richard D. Hayes, Ph.D.
Joint Genome Institute / Lawrence Berkeley National Lab
http://phytozome.jgi.doe.gov

**Comment by cmdcolin** [comment]
That's also a good point but I guess it would be nice for the generate-names script to follow additional includes directives contained in the trackList.json/tracks.conf

 Of course "trackList.json"/"tracks.conf" are the defaults and they don't even have to exist since they are specified in the root config, but i think most jbrowse scripts currently assume they do exist. The alternative is doing what things like add-bam-track.pl do which is to explicitly specify the path to the config files, but i actually prefer the generic --out directory parameter and assuming trackList.json/tracks.conf exist :)

**Comment by carrere** [comment]
Here is what I do (really quick and dirty) to deal with included .conf files in the GenomeDB.pm module:

```perl
sub trackList {
    my ( $self ) = @_;
    my $json_tracks = $self->{rootStore}->get( 'trackList.json', { tracks => [] } )->{tracks};
    #my $conf_tracks = $self->_read_text_conf( 'tracks.conf' )->{tracks} || [];
    
    my $dataDir =  $self->{dataDir};
    system ("cat $dataDir/*.conf > $dataDir/tmp.conf");
    my $conf_tracks = $self->_read_text_conf( 'tmp.conf' )->{tracks} || [];
    system ("rm $dataDir/tmp.conf");
    
    return [ @$json_tracks, @$conf_tracks ];
}
```

**Comment by carrere** [comment]
Thanks @rbuels for the fix !
