### ISSUE TITLE
A way to shorten entries in faceted track selector

### ISSUE THREAD

**Issue by scottcain** [GMOD/jbrowse#558]
In the WormBase JBrowse (http://jbrowse.wormbase.org/), there is a metadata entry for "citation" where background information about the track and it can be fairly long.  Is there a way that some of that content can be hidden but still searchable?  Currently, with the long citations, I can only see one track at a time most of the time, which makes for a strange UI.

**Comment by cmdcolin** [comment]
Wow...that looks pretty crazy...is that the intention or do you want the shortened description?

As far as this goes:
> Is there a way that some of that content can be hidden but still searchable?
You could try to use a combination of trackMetadata.indexFacets and trackList.displayColumns to index the facets but only display certain columns.

**Comment by vivekkrish** [comment]
Here is an example of what we have done for the Araport JBrowse instance,
hiding the publication title but indexing it so that it is searchable:
https://github.com/Arabidopsis-Information-Portal/jbrowse-contrib/blob/master/jbrowse-contrib/data/json/arabidopsis/trackList2.json
https://github.com/Arabidopsis-Information-Portal/jbrowse-contrib/blob/master/jbrowse-contrib/data/json/arabidopsis/epiccogeMetaData.csv

**Comment by cmdcolin** [comment]
@vivekkrish: so this uses indexFacets and displayColumns to accomplish this? that's great. I was sort of wondering if that would work.

I guess one consideration is that the "indexFacets" appears to be part of trackMetadata, so does it have to be in an external csv? I think Scott's are in the "metadata" section of JSON

**Comment by cmdcolin** [comment]
I think we have resolved this in a couple scenarios, suggest close :)

And RE my last post, indexFacets can be used even if the displayed column isn't present :)
