### ISSUE TITLE
The generate-names.pl --workdir parameter is a little dangerous

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#563]
I realized when I saw a mailing list thread where someone misused the --workdir parameter that it is a little dangerous after it was re-added to JBrowse 1.11.6

People might mistake it's meaning and point it to a directory where some data that they want indexed. It will actually delete all that data and they will be very sad.

Instead of removing all data, it could just remove any old hash files.

**Comment by enuggetry** [comment]
I find that if --workdir is not specified, it uses the data/names dir and creates a number of log files, which are eventually cleaned.  If --workdir is specified, log files are created in the specified workdir and cleaned before the empty() method is called , which does the dangerous deeds.
Colin and I had a little discussion as to whether we should rename the option to --tempdir, reflecting the temporary nature of the content; or to remove it all together, given remoteness of anyone actually needing the feature.
In the end, here, I think I'll keep it simple and remove the call to empty(), affecting only one line in one file with no other changes to documentation or otherwise, and leaving the option for any future esoteric needs.

**Comment by cmdcolin** [comment]
I think the "empty" flag has sort of a different purpose and we might still want it.

Basically, the contents are normally re-indexed when generate-names.pl is called, and so the empty flag is turned on by default.

Otherwise, if the --incremental flag is on, then the empty flag is turned off.

Therefore, I think this change kind of makes all the generate-names.pl calls incremental which might not be desirable.

**Comment by cmdcolin** [comment]
Here's the line where the empty parameter is set on the hashstore https://github.com/GMOD/jbrowse/blob/master/src/perl5/Bio/JBrowse/Cmd/IndexNames.pm#L228

**Comment by enuggetry** [comment]
I see. ok.  preserve the rmtree on the names dir but remove it on the
workdir.
presumably there's no safety issue on the names dir, since we expect we are
creating the names dir.
I see why --workdir might have been removed.  It seems rather remote that
anybody would use an important dir as a workdir.
If you have no objection, I think I'll just remove the --workdir option.

**Comment by cmdcolin** [comment]
I think it might be ok but here is where the --workdir flag was originally suggested https://github.com/gmod/jbrowse/issues/273

The hashing strategy has changed since this issue was made so it may not be relevant anymore
