### ISSUE TITLE
Unknown BAM tag type 'B', tags may be incomplete

### ISSUE THREAD

**Issue by mjafin** [GMOD/jbrowse#568]
Hi There,
Really liking JBrowse, but had recently some Ion Torrent bam files come in that don't show base changes in JBrowse. MD tags are there but error console says "Unknown BAM tag type 'B', tags may be incomplete". The reads look generally like this:
```
6WI5R:07600:06479       0       chrM    12975   9       26M5S   *       0       0       ACTAGGCCTCCTCCTAGCAGCAGCAGCAATC <====9<9<<8:;6;=;=<<<;;9-+**(**  ZP:B:f,0.0043055,0.00434245,0.000556284 ZA:i:124        ZG:i:225        ZB:i:30 ZC:B:i,225,223,1,0       ZM:B:s,254,4,216,38,-4,252,4,280,494,-10,28,24,254,-30,232,494,8,504,-12,0,260,276,216,222,210,8,10,232,240,12,-4,-2,266,274,-28,462,24,0,484,44,238,516,228,0,-20,-14,550,-42,222,34,44,240,0,12,204,18,10,6,22,8,248,218,260,276,-44,242,32,212,92,-14,276,-16,-40,-12,-16,-18,226,310,364,518,146,184,56,198,-50,150,120,10,4,12,0,-58,830,446,-32,58,386       ZF:i:27 RG:Z:6WI5R.IonXpress_026        PG:Z:tmap       AS:i:26 XM:i:26 XA:Z:map4-1     XS:i:22 NM:i:22 MD:Z:0T0A0C0T0A1G1C0T1C0T1C0T0A0G0C0A0G0C0A0G0C0A0
```
I think JBrowse doesn't dig the extra information padded in Ion Torrent BAM files. Is there anything that can be done to make it ignore the offending tags and display the base changes correctly? It seems to read the CIGAR a-OK as I can see locations of indels.

**Comment by keiranmraine** [comment]
Hi Miika,

I can't fix this but I can diagnose for someone who has the JS skills.  There is nothing wrong with your BAM records (according to the spec):

![screen shot 2015-03-05 at 09 33 31](https://cloud.githubusercontent.com/assets/3740323/6502368/c6fc38cc-c31a-11e4-87a0-964832549773.png)

It looks like this has been in the spec since 2011, but I don't know when the core BAM parsing code was written:

https://github.com/samtools/hts-specs/blame/master/SAMv1.tex#L412

P.S.  Although there's nothing wrong with the format of the SAM record I'd be a little concerned about it being mapped (even with MAPQ=0) with only 4/26 bases matching and 5 soft clipped.

**Comment by mjafin** [comment]
Thanks @keiranmraine. I actually just pulled a random read from the file so this is probably not representative of the overall quality - just an example to highlight a possible problem in the way JBrowse parses bam files.

**Comment by cmdcolin** [comment]
Ref #783 fix
