### ISSUE TITLE
BAM files partially displayed (on example data set)

### ISSUE THREAD

**Issue by anaome** [GMOD/jbrowse#574]
Hello there,

I am currently stuck at the stage of properly visualising the Volvox example data set in a freshly installed Jbrowse (with Firefox 34.0 in Bio Linux 8.0.5 on a Virtual Box 4.3.26).

All tracks which are loaded through the tracks.conf file print the same `Unable to fetch...` error message, that is for BAM, GFF3, GTF, VCF, BW tracks.

I solve the problem by updating to Firefox version 37.

There remains however a few problems with the BAM tracks:

1) The tracks do not seem to load entirely:
![screenshot1](https://cloud.githubusercontent.com/assets/11611496/6941483/bd0a4c3e-d880-11e4-8bf3-e1b0b24233df.png)

printing errors like `invalid BGZF block header, skipping" Uint8Array [ 160, 38, 99, 73, 21, 23, 11, 251, 248, 70, 8 more… ]`

2) At the zoom level at which it should switch between individual reads displayed to coverage density, `Error: integer overflow` appears.
![screenshot2](https://cloud.githubusercontent.com/assets/11611496/6941622/a70235ae-d881-11e4-95c4-1d0f346854f5.png)

printing error `cannot get size of BigWig/BigBed file, widest zoom level not available`.

Could anyone help me on that?
Thank you in advance

Aymeric

**Comment by cmdcolin** [comment]
This is a little bit of a subtle distinction, but you are accessing jbrowse using the "filesystem" instead of through a proper http server (see the file:/// in the url instead of http:// like a normal website)

JBrowse needs a proper http server to return certain types of ajax calls, particularly ones for the BAM files.


I would do the following
* install apache using sudo apt-get install apache2
* move the JBrowse-1.11.6 folder from /var/www/ to /var/www/html
* open JBrowse using http://localhost/JBrowse-1.11.6

**Comment by anaome** [comment]
I did what you said and it works !
Thanks a lot!
