### ISSUE TITLE
View track labels should be off by default

### ISSUE THREAD

**Issue by selewis** [GMOD/jbrowse#578]
1. Because these obscure the presentation of the actual features. Stealing screen real estate that is more useful for seeing features
2. Because users/biologists are highly unlikely to discover the largely hidden, non-intuitive menu item for turning these off.

**Comment by colindaven** [comment]
You can change this in your trackList.json config files with thwe showLabels tag. 
      {
         "style" : {
            "className" : "feature",
            "showLabels" : false 
         },

I preconfigure many tracks according to user feedback and usefulness of the information. In many cases it is imperative to show this information, so the default works great.

I would definitely prefer to avoid having this changed.

**Comment by cmdcolin** [comment]
@colindaven  this feature is actually for hiding the track labels instead of the feature labels. It is actually implemented in GMOD/Apollo only right but we have considered backporting it  for core jbrowse for awhile too (see #490) and it has been improved so that it should be ready for that

See the View menu here http://icebox.lbl.gov/WebApolloDemo/jbrowse/?data=http%3A%2F%2Fjbrowse.org%2Fcode%2FJBrowse-1.11.6%2Fsample_data%2Fjson%2Fyeast&loc=chrI%3A92094..138135&tracks=DNA&highlight=

**Comment by rbuels** [comment]
Well, we have a button in core now to hide track labels, that's probably as close as we can get to pleasing everybody on this.
