### ISSUE TITLE
help for adding file support and track display

### ISSUE THREAD

**Issue by zym618** [GMOD/jbrowse#581]
![image](https://cloud.githubusercontent.com/assets/9545816/7138528/81d80cfa-e2f3-11e4-8ad3-da62e085c33e.png)
1.because of positive and negetive number are exist at one site, i use two tracks to display it.now i want to bring this two tracks together.
2.i would like to customize the track to make a different display type when zoom in.(Like gff3 file, when zoom in it shows the gene)
by reading http://gmod.org/wiki/JBrowse_Configuration_Guide i know maybe i should write a plogin
have been learning dojo for a long time,still don't know how to do that
so where could i modify the bigwig file display type 
or a demo would be great.

**Comment by cmdcolin** [comment]
1. I am not sure if this can be done currently. I think it would be a great idea though. I think the idea of having "subtracks", i.e. two different files in one track, is one that has been highly requested.

2. CanvasFeatures tracks can do part of the functionality that you are interested in (e.g. bigwig when zoomed out, features when zoomed in). See http://gmod.org/wiki/JBrowse_Configuration_Guide#Configuring_Summary_Histograms 

If I remember correctly though, the summary histogram bigwig is less fully featured than a normal BigWig track, so I don't think it can do as fancy of a display as how you describe it.

**Comment by zym618** [comment]
First of all, thanks for your answer to my question.

2.i find a similar track in http://tools.genxpro.net/apadb/browser/hg19/?loc=chr1%3A61502241..63293800&tracks=DNA%2CpolyaDb&highlight= which is histogram when zoomed out, position with arrowhead when zoomed in.
i see the track configuration and find that the urlTemplate is trackData.json
by reading http://gmod.org/wiki/JBrowse_Configuration_Guide#Lazy_Nested-Containment_Lists_.28LazyNCList.29 ,  the format of trackData.json is too complex for me.
so is there any perl script to transfer the format directly?
i have bedgraph format file like this
![image](https://cloud.githubusercontent.com/assets/9545816/7177670/0b5c0b9e-e45b-11e4-9fce-cb51ab2dc36f.png)
and also have bigwig format file

**Comment by cmdcolin** [comment]
Technically the types of histograms that are shown on that browser that you linked to are auto-generated when you run flatfile-to-json.pl. The thing that I was talking about is for when you want a custom BigWig histogram (often used on BAM files for coverage, because BAM files don't have  a preprocessing step). You can still use a custom bigwig if you want, but the histograms should be autogenerated if you are using flatfile-to-json.pl

Note: If you are finding that your histograms are not being displayed automatically, you can try and adding  "maxFeatureScreenDensity" or "featureScale" settings to your track in trackList.json. If you make featureScale something like 0.1, then it will draw the histograms unless until your zoom level is much closer to the "base level" (the units for the featureScale is "pixels per basepair")

**Comment by zym618** [comment]
really really thank u, it helps me a lot.
i have been successfully create the track that i need.
help me close the issue,  i couldn't find where to do that.

**Comment by cmdcolin** [comment]
Glad I can be of help and that it worked for you :)
