### ISSUE TITLE
Add tracks parallelly and copy Jbrowse from remote host

### ISSUE THREAD

**Issue by verne91** [GMOD/jbrowse#583]
Hi,
1. As I have too many bed tracks to add to the Jbrowse and each one cost almost 1 hour, can I add these tracks parallelly?
2. The computing resource of my web server is samll, can I configure the Jbrowse and add tracks in remote host and copy the whole directory to the web server? In other words, do the Jbrowse need to use the bed files in the disk after adding them with flatfile-to-json.pl?

B.W.

**Comment by cmdcolin** [comment]
@rdhayes Do you have any recommendations on the parallel running?

**Comment by rdhayes** [comment]
The BASH scripts I am forever neglecting to share are very specifically
geared towards running GFF3 to JSON conversion in parallel on an SGE
cluster.

I can finally share them if this might help. Should be easy to adapt them
to convert BED to JSON instead, and to run on a local machine rather than
submit cluster array jobs. Let me know where the best location in the
github tree for this might be.

Sun Chen, is this feature rich BED? My own experience with that format has
been really just bedgraph data, which is more amenable to conversion to
BigWig format for JBrowse.


Richard D. Hayes, Ph.D.
Joint Genome Institute / Lawrence Berkeley National Lab
http://phytozome.jgi.doe.gov

**Comment by verne91** [comment]
Hi, @rdhayes 

My bed files are not rich BED. Below are some samples.
chr01   66761   66844
chr01   67233   100667
chr01   100668  102930
chr01   102935  107330
chr01   107389  107472
...

The first column is the chromosome number. The second column is the start position of the feature and the last column is the end position of the feature.

Can your BASH scripts handle my files?

**Comment by cmdcolin** [comment]
Just for reference, the  BEDTabix parser would be a good option for this type of large BED file, it is faster than running large BED files through flatfile-to-json.

BEDTabix is on master, not yet released though

**Comment by healthfreeak1** [comment]
My bed file are not giving visual output. As i import them in jbrowse. It shows the name in the left side but no visual output in right side. Can you tell How to resolve this problem?

**Comment by cmdcolin** [comment]
@healthfreeak1 possibly your chromosome names do not match http://gmod.org/wiki/JBrowse_FAQ#After_I_load_my_track_it_appears_in_the_tracklist.2C_but_the_track_appears_empty

**Comment by cmdcolin** [comment]
Possibly another thing is a javascript error. Try looking at the javascript console

**Comment by cmdcolin** [comment]
Could refer to BEDTabix instead of flatfile-to-json.pl in parallel. BEDTabix much faster to create...pending release :) maybe close for now
