### ISSUE TITLE
how to visualize sub-features of sub-features (e.g. stop_codon_read_through features from Web Apollo)

### ISSUE THREAD

**Issue by mpoelchau** [GMOD/jbrowse#584]
Hi everyone,

I'd like to load data derived from Web Apollo output into Jbrowse as a static track. This particular dataset also has stop_codon_read_through features, which are child features of the CDS. I haven't found a way to specify sub-features of sub-features in trackList.json. Is there a way to do this in Jbrowse that replicates the way stop_codon_read_through features are visualized in Web Apollo? 

Thanks!

Monica

**Comment by cmdcolin** [comment]
Good question, this is actually a tricky problem. It's true that the exported GFF3 of WA includes these readthrough's as a subfeature-of-a-subfeature. This causes problems when it is loaded back into JBrowse...

For context, the exon and CDS are both just one-level subfeatures of the mRNA. But with the two-level-subfeatures problem, the stop_codon_read_through is a subfeature of the CDS, and it is never rendered  because renderSubfeatures isn't called recursively. 

Why is it that WA can render the readthrough stop codons then? It's because it does not consider the  stop_codon_read_through as a subfeature-of-a-subfeatures

The easiest way to fix the problem right now is to make the readthrough stop codon a child of the mRNA. Whether we should do this in WA is now up to debate, and might want cross-posting

**Comment by childers** [comment]
Hi Colin,

I agree that adjusting the parent to be the mRNA is the most
straightforward fix, but the resulting features would no longer follow the
way the sequence ontology
<http://www.sequenceontology.org/browser/current_svn/term/SO:0000883>models
this relationship. I think you are right that this deserves more
discussion.

Chris

**Comment by mpoelchau** [comment]
Thanks for the response, Colin! I was hoping to not have to modify the gff3 file (also for the reason that Chris mentions), but that's what we've done in the interim, and it seems to work thanks to Chris adding a new CSS style:
https://apollo.nal.usda.gov/cimlec/jbrowse/?loc=Scaffold2%3A8879186..8879343&tracks=DNA%2CAnnotations%2Cclec_OGS_v1.2&highlight=

**Comment by selewis** [comment]
To me this appears to be a bug in JBrowse. We need to talk to Eric about
it. It shouldn't be on us to kludge around a JBrowse issue.

-S

**Comment by mpoelchau** [comment]
Thanks, @rbuels!
