### ISSUE TITLE
Adding google analytics to jbrowse

### ISSUE THREAD

**Issue by lpryszcz** [GMOD/jbrowse#589]
Is it possible to add google analytics code for traffic tracking?

**Comment by enuggetry** [comment]
Hi Leszek,


In src/JBrowse/Browser.js you can add your google analytics ID.
search for "google analytics"

Eric Yao

**Comment by lpryszcz** [comment]
Hi Eric, 

I've changed 
```var _gaq = _gaq || []; // global task queue for Google Analytics```
to 
```var _gaq = _gaq || [['_setAccount', 'UA-XXXXXXXX-2']]; // global task queue for Google Analytics```
but I don't see any traffic in Real-time Analytics report. 
Do I have to specify anything else?

**Comment by nathandunn** [comment]
Typically it takes about 24 hours for you to see any data.

**Comment by cmdcolin** [comment]
Also modifying the Browser.js directly also won't work if you have the release version (the code is minified so modifying the original file won't have any effect [subtext: we should probably just remove the original files in the release version to reduce confusion])

**Comment by cmdcolin** [comment]
Might be easier to add it directly to index.html if using the release version currently

**Comment by enuggetry** [comment]
Yeah, easier to put it in index.html.
But, this was something that was shaking around in the back of my head:

There may some issues with ga.js and multiple tracking codes.  Browser.js
injects is ga.gs.  So, use the other in index.html.
https://support.google.com/analytics/answer/1032400?hl=en

**Comment by enuggetry** [comment]
Another reason to keep the ID in browser.js intact is it's a real jbrowse
ID for the project (i assume).
If you change it, you would effectively go stealth from the jbrowse project.

**Comment by vivekkrish** [comment]
For the JBrowse running at the Arabidopsis Information Portal (https://apps.araport.org/jbrowse/?data=arabidopsis), we resorted to inserting the GA tracker code into the index.html like so: (https://github.com/Arabidopsis-Information-Portal/jbrowse/blob/stable/index.html#L109-L130).

However, we also had to toggle `suppressUsageStatistics` to `true` because the method `_reportCustomUsageStats()` phones home to a service located at jbrowse.org, which is served over standard *http*, and is blocked because our JBrowse is served over *https* (since browsers disallow mixed content).

**Comment by lpryszcz** [comment]
Thanks, adding code to index.html works fine! 
Good point about http/https problem. Luckily, I'm using http only, but I'll keep it in mind! 
btw: I'm using release version.
