### ISSUE TITLE
generate-names.pl

### ISSUE THREAD

**Issue by thomasvangurp** [GMOD/jbrowse#591]
Dear Developers,

Would it be possible to include autocompletion on words in feature Description/Alias?  For example, for a gene named Beta-1,3-N-Acetylglucosaminyltransferase family protein i would love the autocomplete to show the gene name to pop up when I start typing "Acetylgluco..." instead of Beta-1.

Kind regards,
Thomas

**Comment by cmdcolin** [comment]
The "Alias" field (the proper alias field in GFF3) is indexed by generate-names.pl by default, so it would be interesting to know if this is not working for you. There are several examples of the Alias field being indexed in the volvox sample for jbrowse (hga and hgb)

The description is not indexed though. Since a description can be fairly long, the "autocomplete" techniques that are currently used not very appropriate. It would be better to have a string similarity approach instead.

**Comment by cmdcolin** [comment]
If there aren't any more problems maybe we can close the issue (note: you could also use the Names REST API to create your own custom service to return string similarity matches for things typed into the jbrowse search box)
