### ISSUE TITLE
CanvasFeature descriptions overlap at high density

### ISSUE THREAD

**Issue by erasche** [GMOD/jbrowse#594]
I looked harder this time, don't think I saw an open issue that's similar to this. Apologies for the dupes in the past.

Rolling over a features seems to trigger a redrawing of the description, but no occlusion is done for the background causing text overlay.

![screenshot from 2015-05-22 16 13 27](https://cloud.githubusercontent.com/assets/458683/7779847/d5d89c08-009d-11e5-8808-140028a20935.png)

Live instance:
https://cpt.tamu.edu/dot/jb/q/?loc=Merlin%3A1..6870&tracks=DNA%2C89b4b9280761aacde16640100508bde7%2Caf15404c6dd609d3861ff788b3b2acc3&highlight=

**Comment by cmdcolin** [comment]
There is the "maxDescriptionLength" variable that could potentially help. There are probably other workarounds too. I guess what i'm saying is that it's hard to know what the "Expected behavior" would be in this case so it might be hard to fix this bug

**Comment by erasche** [comment]
Okay, not a problem. Just figured I'd report this unexpected labelling issue.

For me, the "expected behaviour" would be that labels don't overwrite one another. Either by whiteing out underneath themselves, or via not plotting anything past some width, if that width starts to overlap.

**Comment by selewis** [comment]
I would pick some relatively short length and add an ellipsis (...) at the
end. If the user clicks on the ellipsis (or the text) it could either show
the full description in a balloon or temporarily heighten the cell.

-S

**Comment by cmdcolin** [comment]
Actually, sort of a similar but different note, but with CanvasFeatures, the maxDescriptionLength is not used. Instead, CanvasFeatures uses maxFeatureGlyphExpansion.

With maxFeatureGlyphExpansion, it only draws "beyond" the feature given by the maxFeatureGlyphExpansion limit (which is measured in scale*basepairs if i remember correctly). If you set maxFeatureGlyphExpansion to 0, then it will only draw the description up to the width of the feature, and add ellipses.

In any case, @selewis advice would be a good addition, because even the popup label will use the "ellipses" instead of giving the full description, sort of a silly artifact as the popup should show the full string probably.

**Comment by erasche** [comment]
Thanks, since this isn't a "bug" so much as a "I should've used this configuration", I'll go ahead and close this issue. 

Anyone object to me updating the gmod wiki JBrowse configuration page with a note on this?

**Comment by cmdcolin** [comment]
Sounds good to me. If you have any proposed fixed to the code too feel free to add to this or new pull request, etc :+1: 

If you don't have access to the wiki @scottcain might be able to help.

**Comment by erasche** [comment]
Already have access, no worries there. I'll get the specific config worked out and some examples added soon. Thanks for the help!
