### ISSUE TITLE
CanvasFeatures track - View Details - sequence boxes exceed container size

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbrowse#596]
In Volvox demo:
Noted on these tracks:
CanvasFeatures - transcripts
CanvasFeatures - mixed mRNA and CDSs

Right click the sequence and select View Details - shows that initially the FASTA sequences are getting clipped on the right side of the dialog box.  Dialog can be scrolled to get view the other side.
![mwsnap 2015-06-01 17_30_20](https://cloud.githubusercontent.com/assets/10053377/7926265/d4c952e6-0884-11e5-9f3e-a9abdf39c37b.png)

Also note that the sequence data box exceeds it's container size.
![mwsnap 2015-06-01 17_31_07](https://cloud.githubusercontent.com/assets/10053377/7926268/d80faa2c-0884-11e5-9b75-c21038e7fa27.png)

These are minor cosmetic problems.
## Preferred remedy:
- Grey containers should fall within the natural horiz width of dialog box such that horiz scrolling would not be required.  (not certain if this is practical because I'm not experienced with all possible content).
- Sequence box widths should be within their grey box containers. (This should be doable).

Noted on Chrome ver 43
Need to verify on Firefox and Chrome

**Comment by cmdcolin** [comment]
+1 had observed this before. it is seemingly just cosmetic but would be good to fix

**Comment by sakshamsaxena** [comment]
Is this still observed?

**Comment by enuggetry** [comment]
yes.  It would be nice to fix it.

**Comment by sakshamsaxena** [comment]
So apparently, the textbox doesn't really overflow the grey area, but instead the whole of grey area is too wide that the horizontal scroll comes in. Tried to adjust some padding and width but didn't see much difference. After much attempts, I realized that the width of the popup is always dynamically adjusted, and it always has insufficient width, so every time we see a horizontal scrollbar. 
Any idea where the config of this popup is written?

**Comment by enuggetry** [comment]
It might be in the Views/Track/_FeatureDetailsMixin.
Perhaps you can make the dialog box not a fixed width, making it conform
the the widest element within?

**Comment by sakshamsaxena** [comment]
Yes exactly that's the plan. I'll send a PR by tonight. Thanks.

Regards
Saksham Saxena
________________________________

**Comment by sakshamsaxena** [comment]
Did some more research on this. The dijit [Dialog Box](https://dojotoolkit.org/reference-guide/1.10/dijit/Dialog.html) actually automatically conforms to the content. The easy way to change this is to specify the width in CSS, but that'll be fixed. Another way would be to change it where the dialog itself is initialised. The file you mentioned has the content of the features which goes into the dialog. I'm not really sure about the structure yet, so it's taking me time to get to the bottom of this.

Otherwise, the CSS changes do work nicely, and would still do because most of the elements inside [have fixed](https://github.com/GMOD/jbrowse/blob/master/css/main.css#L871) width nonetheless.

So I can send a PR with a single line change, alright, but still would like to know more on the structure. Refer me something maybe? Let me know what you think.

**Comment by enuggetry** [comment]
Getting it at the root sounds like a good idea.
Try searching for "View Details" in the code. that's where you should fine
the event handling setup for the menu item.

**Comment by sakshamsaxena** [comment]
This seems to be an inherent bug in Dialog. Large content is always scrolled both vertically and horizontally because of poor calculations of width of both content and window. So the expected behaviour of Dialog window to conform to the content is not always seen. See [this demo](https://dojotoolkit.org/reference-guide/1.10/dijit/Dialog.html#terms-and-conditions-dialog) on their docs, which has the same problem as we do. 
Meanwhile, I've come up with a good workaround, targeting this Dialog only. Let me know what you think.
And I'm not so well versed with Dojo Toolkit so please bear with me :sweat_smile:

**Comment by enuggetry** [comment]
I see.  Glad you found a solution.
