### ISSUE TITLE
Volvox works but my track not

### ISSUE THREAD

**Issue by lfaino** [GMOD/jbrowse#599]
Dear,
today I was trying to install JBrowes but I had a problem. When I run the setup script, the tracks are displayed correctly while if I run the prepare-reference script on my fasta file do not work. 
interestingly, if  I add a line in the setup.sh file to prepare my own reference fasta and I let to prepare the file in the sample folder, than the reference is displayed correctly.

Any idea?

thanks
Luigi

**Comment by cmdcolin** [comment]
Do you have any more details on what wasn't working? Normally, prepare-refseqs.pl will output to a data directory specified in the current directory, which is normally the jbrowse root (i.e. wherever you unzipped it to)

If it was outputted to a different place, you may have to use prepare-refseqs with the --out parameter to specify the directory of interest

**Comment by lfaino** [comment]
hi, 
I did some more debug and the problem is a bit more complicated. I`m trying to install webapollo 2.0 and jbrowse is part of it. 

so, here the problem.
if i install jbrowse in the $tomcat/webapp folder, then all it is working. I can see the reference sequence after the prepare-refseq and when I browse localhost:8080/jbrowse
however, if I use the prepare-refseq in the $tomcat/Apollo/jbrowse  and I browse to localhost:8080/Apollo/jbrowse I can not see the reference. 
on the other hand if i run the setup.sh and i navigate to localhost:8080/Apollo/jbrowse/index.html?data=sample_data/json/volvox it is working again.

Any idea?

thanks
Luigi

**Comment by cmdcolin** [comment]
Sorry, this is a little confusing, so I'll try and do this sort of step by step

Basically, WebApollo is a java web application, and when you deploy a java web app, you just copy the WAR file to the $tomcat/webapp folder, and you don't actually modify any other contents of the webapp folder


So, after you have setup your webapollo WAR file (using apollo deploy or similar), you just copy the war file to your webapp folder. Then,  the easiest way to tell WebApollo where your data directory is to use the "Create Organism" form (see picture from http://webapollo.readthedocs.org/en/latest/Apollo2Build/)
![test](http://webapollo.readthedocs.org/en/latest/images/2.png)


I am just telling you these details since tomcat normally isn't used for just copying files into the webapp folder; normally, you deploy a "war file" into the webapp folder, so the deployment process is sometimes unfamiliar. However, it does make things simple in some ways, and then WebApollo will take care of the jbrowse installation automatically, so you don't have to copy your jbrowse into the webapp folder yourself.

Feel free to chat with us on the Apollo board as well if this isn't clear

**Comment by cmdcolin** [comment]
If there are any other issues let us know! Otherwise I would recommend posting on the apollo board
