### ISSUE TITLE
add --config option in add-bw-track.pl and add-bam-track.pl

### ISSUE THREAD

**Issue by childers** [GMOD/jbrowse#620]
Hi there,
I'd like to request support for the --config option for adding bam and bigwig tracks, similar to what is available in flatfile-to-json.pl. My main reason for this is so that I can incorporate all of the track metadata at load time, instead of requiring a post-processing step after adding the track.

**Comment by enuggetry** [comment]
Colin proposed these workaround solutions.  Would these suffice?

Since he explicitly mentions using metadata, i would recommend using trackMetadata.csv instead of adding the metadata directly to trackList.json
http://gmod.org/wiki/JBrowse_Configuration_Guide#Loading_Track_Metadata_from_Files

Alternatively, use the tracks.conf format, which is quite easily editable using simple text processing tools

**Comment by cmdcolin** [comment]
^^Just to add to that, I definitely agree that the ability to automate all the imports is a great idea but the add-bam-track and add-bw-track are a little more scrappy than the flatfile-to-json. You could manually flesh out the json for your track with bin/add-track-json.pl and then automate it that way too! That way it can be automated but then you have a little more control over the config

**Comment by childers** [comment]
Hi Colin, I keep forgetting about add-track-json.pl, thank you for reminding me! I'll look into it (again).  I also add other information, such as track specific styles, and category tags, which goes outside what the metadata .csv file supports.
@enuggetry is there an alternative workflow to flatfile-to-json.pl to programmatically create and populate the tracks.conf file?

**Comment by enuggetry** [comment]
I'm not aware of an alternative workflow.

**Comment by childers** [comment]
Thank you for confirming my what I found too.  It seemed strange to me to have two separate configuration systems, but only workflows that make use of the older one. Were there ever plans to try migrating the track generation to the newer system?

**Comment by cmdcolin** [comment]
(my opinion) I think both configuration systems have advantages, so it is probably not worth it to "migrate" completely to conf format.  It is just a simple (but fully featured) format that makes certain things easier, like defining a track by hand, and supporting multiline functions, etc. but it is a fully custom format, so supporting a standardized format like the json is good. And since both of them can coexist not much reason to migrate.



Nevertheless, there is the bin/json2conf.pl script in the bin directory if you want to migrate a particular tracklist.json instance

**Comment by cmdcolin** [comment]
Another request for this!

http://gmod.827538.n3.nabble.com/Gmod-ajax-add-configuration-pieces-to-an-existing-track-configuration-td4051551.html
