### ISSUE TITLE
[BAM Coverage] Coverage wrongly visualised for spliced alignments

### ISSUE THREAD

**Issue by lpryszcz** [GMOD/jbrowse#645]
I've noticed coverage is wrongly displayed from BAM files for spliced alignments. You expect no or lower coverage for introns than for exons. 

http://zdglab.iimcb.gov.pl/jbrowse/?data=data%2FGRCz10&tracks=DNA%2Cgene%2CmRNA%2CRZE024_bam_cov%2CRZE024_bam&loc=5%3A23582706..23585281&highlight=

**Comment by cmdcolin** [comment]
If you use the "SNPCoverage" track type instead of "FeatureCoverage", then it is easier to see the spliced alignments. Not totally what you want though.

Alternatively, you can generate bigwig files to indicate coverage. Using a pipeline of BAM->BedGraph->BigWig is pretty good with the combination of "bedtools genomecov" with the BAM file as input (make sure to use the -split option),  and "bedGraphToBigWig" to make the conversion to bigwighttp://bedtools.readthedocs.org/en/latest/content/tools/genomecov.html


http://gmod.827538.n3.nabble.com/Gmod-ajax-Question-on-Read-and-coverage-Display-td4051758.html

**Comment by lpryszcz** [comment]
Thanks Colin! Actually, I do have bigwig track with correct coverage. Just wanted to report there is an issue with that, but I see you are already aware of it. 

http://zdglab.iimcb.gov.pl/jbrowse/?data=data%2FGRCz10&tracks=DNA%2Cgene%2CmRNA%2CRZE024_bw_xy_neg%2CRZE024_bw_xy_pos%2CRZE024_bam_cov%2CRZE024_bam&loc=5%3A23581656..23587475&highlight=
