### ISSUE TITLE
Phantomjs not rendering NeatHTMLFeatures introns

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbrowse#651]
Phantomjs not capturing NeatHTMLFeatures introns properly.
![phantomjs bad introns](https://cloud.githubusercontent.com/assets/10053377/10922983/3b7bd234-8233-11e5-8864-1a6d2523f853.jpg)

This probably has to do with use of SVG viewport function.

https://github.com/ariya/phantomjs/issues/11956

Phantomjs 2.0.0

**Comment by cmdcolin** [comment]
I believe safari also doesn't render it, probably due to same rendering engine

**Comment by enuggetry** [comment]
There's some evidence that it might not be a rendering engine issue.  I grabbed the SVG code to render under JSFiddle and it rendered just fine.  This suggests that their might be environmental factors, like some combination of tags/styles causing the problem.

**Comment by cmdcolin** [comment]
I made some experiments with neatfeatures to make them into track types rather than using lang.extend techniques on the track types

https://github.com/GMOD/jbrowse/tree/track_type_neatfeatures 
![jbrowse](https://cloud.githubusercontent.com/assets/6511937/24208361/d4b82e3a-0ef9-11e7-9659-d5d850a1b2bd.png)

this had the side effect of fixing this bug!

**Comment by cmdcolin** [comment]
If there is interest I can open a PR for the linked branch

**Comment by enuggetry** [comment]
It looks good, please do open a PR.  thanks.
