### ISSUE TITLE
Touchscreen support seems to be broken

### ISSUE THREAD

**Issue by ihh** [GMOD/jbrowse#694]
Touchscreen support was added in release 1.11.5 (per release-notes.txt) but seems to be broken in 1.12.  Specifically, on my iOS devices, left & right swipes do not pan the view.

**Comment by cmdcolin** [comment]
I think this might be the same issue as this one https://github.com/GMOD/jbrowse/issues/637


The 1.11.5 fix was something different (it used to be a blank screen) but that the swiping bug I think only affects newer ios devices. I believe updating dojo libraries can fix it, and so that's what this pull request is about (https://github.com/GMOD/jbrowse/pull/666).

This dojo thread discusses that too https://bugs.dojotoolkit.org/ticket/18168

**Comment by cmdcolin** [comment]
Should be fixed in 1.12.1! Works on ios simulator for me at least. Thanks @enuggetry for getting that out
