### ISSUE TITLE
Abstraction layer to talk to Job Control Systems

### ISSUE THREAD

**Issue by erasche** [GMOD/jbrowse#695]
> Our current plan is to write a (thin) abstraction layer that allows JBrowse to talk to Galaxy or other web shells for job control.

As y'all've figured out, this is incredibly exciting to me :) I'd opened https://github.com/galaxyproject/galaxy/issues/1524 for this exact use case from the Galaxy side.

Please let me know how I can support JBrowse more from the Galaxy end! I'd love to have deeper integration. Galaxy needs an improved Genome browser and the built-in one doesn't receive nearly enough love, when compared to JBrowse and all the awesome plugins that exist.

If it's real life testing, job control system server mocking, etc, happy to help.

**Comment by enuggetry** [comment]
I'll explore some integration with Galaxy, myself.  Like.

**Comment by ihh** [comment]
@erasche it's really exciting that you're interested - we are big fans of your contributions. We are for example using your Docker image!

The first steps towards doing this are underway, for example we now have some experimental code for server->client messaging on the 'faye' branch, allowing the server to notify the browser of new tracks: https://github.com/GMOD/jbrowse/tree/faye/src/faye

This is still very bleeding-edge and incomplete (for example, at the moment, it is hugely susceptible to cross-site forging since we have not yet implemented authentication... the mechanism for replacing/deleting tracks is also not there yet, and there are various other missing pieces)

However it may give some idea of where we are going. @enuggetry is looking into the Galaxy integration so we will definitely be asking for your help/opinions there!

**Comment by rbuels** [comment]
This is coming out in the server-side components and client-side plugin @enuggetry is working on!

**Comment by erasche** [comment]
What I didn't write in the initial issue (but meant to), I'll write now:

*Please for the love of all things good and holy don't re-implement talking to job queues.* Galaxy already handles a huge amount of edge cases for talking to job control systems, it would be in your best interests to write Galaxy tools, and talk to the Galaxy API instead of trying to re-implement all of this in server-side JBrowse.

**Comment by rbuels** [comment]
Cc @enuggetry

+2 points for good use of “for the love of god”

**Comment by enuggetry** [comment]
Yes, it does just that: it uses Galaxy API to execute a workflow.

**Comment by erasche** [comment]
Great! Any possibility it could be done from client side (instead of / in addition to) server side?

**Comment by enuggetry** [comment]
You mean call galaxy from the client side?
I guess we would have to somehow use the galaxy client session or use the galaxy api key, which we shouldn't use through the client session.  But, I think this is a different project that would be interesting.

**Comment by erasche** [comment]
Yeah, call galaxy's API from client side, using API key or something. But yes, maybe separate to your backend implementation.

**Comment by enuggetry** [comment]
If Galaxy could serve JBrowse, like through a /jbrowse route, then we'd be operating under the same client session as the galaxy client session.

**Comment by erasche** [comment]
To me, this would be less appealing from both the galaxy perspective (having to make modifications to Galaxy and tying together two separate services) and the changes to jbrowse serving perspective (It's great serving it from s3 and I'd rather not lose that.)

I'd much rather have jbrowse talking to galaxy with a scoped API key than with more privileged access that a shared session would imply. This way if this feature becomes really popular then I can run tools on my galaxy without auditing the entire jbrowse codebase that's running on that site to ensure it isn't doing anything malicious or is compromised and might delete all of my data.

**Comment by rbuels** [comment]
This is in JBConnect's scope, what do you guys think about closing this one in core JBrowse?
