### ISSUE TITLE
Questions for understanding CanvasFeatures

### ISSUE THREAD

**Issue by clb1000** [GMOD/jbrowse#703]
Hi JBrowse (cmdcolin),
    Thank you for quickly answering my post yesterday about CanvasFeatures. In your response, you indicated the need to update the documentation. While you're thinking about documentation, I'd like to bring up a larger issue from the point of view of somebody who is new to JBrowse but not new to software and programming. The issue is that the proper use of CanvasFeatures is quite difficult do understand from the current documentation and examples. Since my confusion is/will be probably shared by other currently new and future new users of JBrowse, I've boiled down my confusion into three main questions that I've written below.
     Thank you for any clarification that you can provide. I apologize if I've overlooked clear explanation somewhere in the documentation.

#####

1a) What is the purpose of the CanvasFeatures Configuration Option "glyph"?

(See http://gmod.oicr.on.ca/wiki/JBrowse_Configuration_Guide#CanvasFeatures_Configuration_Options)
When I try the value "ProcessedTranscript" that is shown as an example in the output of the commandline
>  flatfile-to-json.pl --help

for instance, the track fails to load and instead just displays "Loading". I've tried other values that I think might be meaningful (eg "Gene"), but same result.

1b) I think the allowed values for "glyph" are Segment, Box, Gene, ProcessedTranscript. When and why would I use them? For example, in a trackList.json file, what should be the effect of including
> "glyph": "Gene"

2) What is the role of "feature" as a key in a trackList.json file? 
For instance, here are three different settings for "feature" from Volvox:
 > "feature": ["CDS", "mRNA"]
 > "feature": "gene"
 > "feature": "mRNA"

  What is being differently accomplished here?

3) When I use flatfile-to-json.pl in conjunction with --trackType CanvasFeatures, the file .../data/trackList.json contains 
 >       "style": {
 >           "className": "feature"
 >       }

"className" is an undocumented "style" element for CanvasFeatures (ie not listed in the table at
http://gmod.oicr.on.ca/wiki/JBrowse_Configuration_Guide#CanvasFeatures_Configuration_Options).
It looks to be used for HTMLFeatures (http://jbrowse.org/code/JBrowse-1.12.0/docs/config.html), so why is it here?

  3a) With "className" here, what is being assigned the class?
  3b) Is there a list of all the legal "className" values?
  3c) The CanvasFeatures on that config.html page use "class": "cds" (or some
  other HTMLFeatures cssClass name), *outside* of the "style" section
  usage. Here's an example snippet:
>     {
>         "feature" : [
>            "CDS:bare_predicted",
>            "mRNA:exonerate",
>            "mRNA:predicted"
>         ],
>         "urlTemplate" : "http://www.ncbi.nlm.nih.gov/gquery/?term={name}-{start}-{end}",
>         "track" : "CDS",
>         "category" : "Transcripts",
>         "class" : "cds",
>         "key" : "CanvasFeatures - mixed mRNAs and CDSs",
>         "trackType": "CanvasFeatures"
>      },

What's going on here with the use of the HTMLFeatures key "class"? Can you tell me where this is documented? Is "class" related to "className" in some functional way?

3d) Does "feature" as used here as a value have any relation to its use as a key in 2) above?

**Comment by cmdcolin** [comment]
1a) Glyphs are a "unit" of drawing in a CanvasFeatures track. It is just code that is responsible for drawing a feature on the screen [1].

1b) Generally I wouldn't manually modify glyph unless needed. Normally you can use the gene glyph and modify the transcriptType and subParts to achieve the right view. Did #701 get fixed by the way?

2) I could be wrong but my general understanding is that this is metadata for biodb-to-json.pl (i.e. it sees the "feature" in the biodb config file, it then loads those feature types from the biodb database and creates the track from it). I guess that this metadata just isn't removed when it goes into the final trackLis.json config. I'd recommend using flatfile-to-json.pl instead of biodb-to-json for more basic use cases

3) The className is unused on the CanvasFeatures. The flatfile-to-json.pl and other programs might output a "style": {"className": "feature"} on CanvasFeatures tracks by default, but it is not used

3a)  The className refers to a CSS class, and only the HTMLFeatures are based on CSS, the CanvasFeatures are not based on CSS, hence, it is unused. So, essentially, 3a 3b 3c and 3b are probably just same answer :)

Footnotes

[1] CanvasFeatures are quite cool and flexible, and the "style" callbacks also make them quite dynamic and configurable (and, you can make your own glyphs too e.g. https://github.com/cmdcolin/sashimiplot). SVG canvas tracks are also being developed so that can add even more possibilities
[2] You also mentioned that you modified the glyph, and then got "infinite loading", but that is probably due to a "javascript crash". It may have violated a unwritten assumption of processedtranscript glyphs. Feel free to make issues for such things, but the javascript console on your browser might have clues too.
[3] The documentation that you linked to is outdated. The main gmod.org wiki has slightly more up to date stuff (not that much different) http://gmod.org/wiki/JBrowse_Configuration_Guide

**Comment by cmdcolin** [comment]
A new jbrowse FAQ got started to try and help with these types of questions! http://gmod.org/wiki/JBrowse_FAQ

I hope that helps. Feel free to ask more questions if interested

**Comment by cmdcolin** [comment]
Closed for now :)
