### ISSUE TITLE
How to add name (of gene or rsid) in Jbrowse tracks?

### ISSUE THREAD

**Issue by man4ish** [GMOD/jbrowse#711]
Hi,

I have succesfully installed Jbrowse and loaded the track after converting them in bed format.

1	14695	35736
1	228291	228654
1	234205	234559
1	321689	331663
1	334155	368597
1	558653	569756

and i got following output.
![screenshot from 2016-03-06 17 33 26](https://cloud.githubusercontent.com/assets/6385968/13554771/e7cbfa06-e3c1-11e5-9ebd-9ebcd53bf05b.png)

while i need name on each id as follows. 

![screenshot from 2016-03-06 17 34 29](https://cloud.githubusercontent.com/assets/6385968/13554772/eb9bf8fc-e3c1-11e5-9a7f-f1ca8af0deda.png)

I have another ucsc file which has such info 

585	chr1_1.1	chr1	-	14695	35736	14695	35736	10	14695,14969,15795,16853,17232,17605,17914,18267,24737,35720,	14829,15038,15891,17055,17257,17742,18061,18379,24891,35736,	0	chr1_1	cmpl	cmpl	1,1,1,0,2,0,0,2,1,0,
586	chr1_2.1	chr1	-	228291	228654	228291	228654	1	228291,	228654,	0	chr1_2	cmpl	cmpl	0,
586	chr1_3.1	chr1	+	234205	234559	234205	234559	1	234205,	234559,	0	chr1_3	cmpl	cmpl	0,
587	chr1_4.1	chr1	-	321689	331663	321689	331663	2	321689,331504,	321818,331663,	0	chr1_4	cmpl	cmpl	0,0,

But how can i use above file to print name on each gene and also arrow direction should be based on strand info. 

Regards

**Comment by cmdcolin** [comment]
@man4ish JBrowse's flatfile-to-json.pl does not support "12 column BED", which is what your data looks like. It only supports 5 column BED

E.g.

Tab separated file, with "chr name", "start", "end", "name", "score"

If you only care about those 5 columns, just use those and it will load the name from column 4


Otherwise,

A) Use ucsc-to-json.pl to load your track. See http://gmod.org/wiki/JBrowse_Configuration_Guide#ucsc-to-json.pl for instructions

or 

B) Convert your data into GFF and use flatfile-to-json.pl on that

**Comment by cmdcolin** [comment]
I presume this is fixed now :) feel free to reopen if not

**Comment by man4ish** [comment]
yes it is fixed.
