### ISSUE TITLE
Error of mismatch display

### ISSUE THREAD

**Issue by yesdanny** [GMOD/jbrowse#750]
Hi All

I used JBrowse-1.11.6 to display the reference sequence and gmap output bam file.
I find 3 errors of mismatch display:

Error 1.mismatch doesn't display
Error 2.mismatch displays, but displays a wrong base
Error 3.match displays as a mismatch

Pic1 and Pic2 are JBrowse display page and corresponding mapping information.

![1](https://cloud.githubusercontent.com/assets/17845039/15652273/a4f8e57a-26b7-11e6-85bb-94c53a0b172f.png)
Pic1

Error 1: Pic1-site1 Chr19:7,189,665 (G-A mismatch doesn’t display)
Error 2: Pic1-site2 Chr19:7,189,656 (A-G mismatch display as A-A)

![2](https://cloud.githubusercontent.com/assets/17845039/15652295/d15f7d18-26b7-11e6-8008-b05c19587583.png)
Pic2

Error 1: Pic2-site1 Chr19:7,190,112 (G-T mismatch doesn’t display)
Error 3: Pic2-site3 Chr19:7,190,152 
There is no mismatch at site Chr19:7,190,152, but a A-C mismatch displayed. I’ve checked my query sequence, the site is really A not C.

Have you ever met these errors and do you have any ideas to solve this problem?
Any help is very appreciated!

Danny

**Comment by cmdcolin** [comment]
There were a couple adjustments to try and fix errors related to clipping of reads in jbrowse 1.11.6 compared with 1.11.5

https://github.com/GMOD/jbrowse/issues/516
https://github.com/GMOD/jbrowse/issues/523

You could try 1.11.5 and see if  it helps. Any example data could help too

**Comment by cmdcolin** [comment]
I was just checking out some comparisons on the volvox sample data between 1.11.5 and 1.11.6 around an insertion site, since I saw those in the original post here, but both of these are seem to be identical.

http://jbrowse.org/code/JBrowse-1.11.5/?data=sample_data%2Fjson%2Fvolvox&loc=ctgA%3A13630..13681&tracks=DNA%2Cvolvox_microarray_bw_xyplot%2Cvolvox-sorted_bam%2Cvolvox-sorted-vcf&highlight=

http://jbrowse.org/code/JBrowse-1.11.6/?data=sample_data%2Fjson%2Fvolvox&loc=ctgA%3A13630..13681&tracks=DNA%2Cvolvox_microarray_bw_xyplot%2Cvolvox-sorted_bam%2Cvolvox-sorted-vcf&highlight=



Would be interesting to see some other sample data or other possibilities

**Comment by cmdcolin** [comment]
In the lack of sample data, can you view the results of your JBrowse BAM data in something like IGV for example? I was just testing out comparing some simulated long read BAM files between jbrowse and IGV and they looked pretty much the same for example, so it would be interesting if there was a discrepancy

**Comment by yesdanny** [comment]
Thanks for your help Colin.
I've installed the latest version 1.12.1 but still found that problem.
I will try to use IGV. Just sooooooo busy these days.
Thank you once again.

**Comment by cmdcolin** [comment]
Any update in this?

**Comment by cmdcolin** [comment]
I would hypothesize that the MD tag was miscalculated on the alignments, i have definitely seen that happen.... if you have sample data to reproduce it or something, feel free to reopen, but maybe close for now :)
