### ISSUE TITLE
NeatCanvasFeatures do not display UTR

### ISSUE THREAD

**Issue by nathandunn** [GMOD/jbrowse#755]
![screen shot 2016-06-02 at 3 22 20 pm](https://cloud.githubusercontent.com/assets/751274/15763004/d20f0c36-28d5-11e6-85ca-a9a9326159aa.png)

**Comment by nathandunn** [comment]
This seems to be fixed as of 9334e76fd7530681fa2dcc71d4440141e1414cfd

**Comment by enuggetry** [comment]
I don't believe it would be fixed (not in the cases that I see).  If the UTRs are not explicitly coded on the ends, it's not going to render anything.  True for both NeatHTMLFeatures and NeatCanvasFeatures.

**Comment by nathandunn** [comment]
Something is working better:

<img width="626" alt="screen shot 2016-12-17 at 1 07 24 pm" src="https://cloud.githubusercontent.com/assets/751274/21289751/cce61478-c459-11e6-9ea8-3dc6da8b0364.png">

from here:

http://icebox.lbl.gov/Apollo2/21/jbrowse/index.html?loc=NW_003571060.1%3A359279..375051&tracks=DNA%2CAnnotations%2CCanvas-MRNA%20-%20GenBank%20TopLevel%2CGenBank%20TopLevel%20MRNA&highlight=

**Comment by nathandunn** [comment]
But,  I don't think the canvas features ever drew UTR's.  However, they are drawing introns.

**Comment by nathandunn** [comment]
Anyway, I'll leave this open for the title, but it still fixes the primary problem with https://github.com/GMOD/Apollo/issues/1090, so I'll leave that closed.

**Comment by nathandunn** [comment]
Sorry, meant open when I said closed.

**Comment by enuggetry** [comment]
The question I have is: if there is a gap between the subfeature and the end of the feature-end, does that imply a UTR is there (as in apple2), though the UTR is not explicitly coded?  The old (non NeatFeature) code drew a line through the entire feature.  
I believe what you show there (that is "fixed") is simply reverting to the original feature drawing engine (with hats disabled).

![ice_screenshot_20161217-165138](https://cloud.githubusercontent.com/assets/10053377/21290694/54a435c4-c479-11e6-816e-1af36a7fd7d4.png)

Sorry for the confusion.
Thanks.

**Comment by nathandunn** [comment]
> On Dec 17, 2016, at 4:58 PM, Eric Y <notifications@github.com> wrote:
> 
> The question I have is: if there is a gap between the subfeature and the end of the feature-end, does that imply a UTR is there (as in apple2), though the UTR is not explicitly coded? The old (non NeatFeature) code drew a line through the entire feature.
> 
Typically the exon coordinates define the transcript coordinates and the UTR that you care about has to be card of a potential coding region.  
> I believe what you show there (that is "fixed") is simply reverting to the original feature drawing engine (with hats disabled).
> 
I think you are correct.  I’m not sure what is going on with Apple 2.   The transcript boundary should match the exon boundary but maybe there is an edge-case that I’m unaware of.  So, on Apple2 the 3’ should not have a space there.  

ctgA:
mRNA: 13000..17200 (+ strand)

The last CDS is:

CDS: ctgA:16500..17000 (+ strand)

But very weirdly no exons are defined, so its not a really biologically relevant example.   Either way they should always look exactly like Apple 3.  

Maybe @selewis may have a thought on this.  


Nathan

**Comment by ihh** [comment]
It might help to see what the types of the "subfeatures" and "features" are here, but in general: UTRs are regions at the 5' and 3' ends of the transcript that are not spliced out (so they should be part of exons), but are not translated either. So e.g. the 5' UTR is the region from the 5' end of the first exon (which should generally be aligned with the 5' end of the transcript) to the start codon (or just before it). And the 3'UTR is the region from (just after) the stop codon, to the 3' end of the last exon (which should generally be the same as the 3' end of the transcript). See image below.

![](http://i.imgur.com/OjYRouN.jpg)

So if you have a parent feature that is an mRNA (transcript), and subfeatures that are CDS which do not quite line up to the full length of the transcript, but no UTRs annotated, then the end-regions of the transcript that are not covered by CDS are by definition UTRs, even though they are not annotated as such.

Things get slightly more complicated if there are exons/introns that are unannotated, because you _can_ have a situation where the start codon isn't in the first exon, which means the entire first exon (and possibly more) are part of the UTR. So if you have a transcript with a CDS but unknown exons, then the part of the transcript before the CDS could either be an intron or it could be a UTR part of an exon, or some mixture of both. It should in any case be rendered as something, so you can see the difference between the transcript and the CDS. I think the Apple3 rendering above is the right way to show it here.

If you have exon annotations, but the terminal exon subfeatures are not aligned with the parent transcript feature, e.g. the start of the 5' exon is not the same as the 5' end of the transcript, then presumably there is an intron right at the beginning of the transcript. I don't know if this does occur in practice (there would be no splice donor site) so I suspect something is wacky here. Again I would favor rendering them as _something_ just to show the difference, and Apple3 looks like the right way to go.

**Comment by nathandunn** [comment]
> If you have exon annotations, but the terminal exon subfeatures are not aligned with the parent transcript feature, e.g. the start of the 5' exon is not the same as the 5' end of the transcript, then presumably there is an intron right at the beginning of the transcript. I don't know if this does occur in practice (there would be no splice donor site) so I suspect something is wacky here. Again I would favor rendering them as something just to show the difference, and Apple3 looks like the right way to go.

Yeah, this is the case for the Apple2.   My intuition is that it shouldn't happen either, but it should be rendered as something as well, but not inferred as a UTR.   I think it might be a slippery slope if we begin to infer errors in the underlying JSON data into a non-error as I think that a biologist would rather have some indication of the error in the data.  However, maybe there is an important use-case / scenario I'm not seeing, either. 

Either way, think we're saying the same thing.

**Comment by cmdcolin** [comment]
There is the impliedUTRs setting which does approximately what was discussed above, but it only exists for canvasfeatures.
