### ISSUE TITLE
Display coding and non-coding transcripts of a gene

### ISSUE THREAD

**Issue by ernestopicardi** [GMOD/jbrowse#757]
Hi all,
I'm new to JBrowse. I’m trying to display all gene features from Gencode Basic V19 annotation (from UCSC). In my gff3, I have the following features: gene – mRNA – ncRNA – CDS – exon - three_prime_UTR - five_prime_UTR ncRNA transcripts include only exons and they appear as an unique box without displaying exons. Is there a way to show protein coding and non-protein coding transcripts from the same gene in different colors?
The trackType is CanvasFeatures.
Many thanks in advance,
Ernesto

**Comment by enuggetry** [comment]
Would utrColor work for you?
 "style": {
    "className": "feature",
    "color": "#E32A3A",  // exon color
    "utrColor": "#0000ff" // utr color
  },

**Comment by vivekkrish** [comment]
Hi @ernestopicardi , I think the issue might be due to how the **Gene/ProcessedTranscript** glyphs work with **CanvasFeatures** tracks. If you look at the config options for [CanvasFeatures](http://gmod.org/wiki/JBrowse_Configuration_Guide#CanvasFeatures_Configuration_Options), you will see the following config parameter:

`transcriptType`: For Gene glyphs, the feature type tag that indicates that a subfeature is a processed transcript. Defaults to **mRNA**.

Since you have 2 different gene hierarchies: gene -> **mRNA** -> exon and gene -> **ncRNA** -> exon, only one type is represented correctly because of the default config.

One way to work around this is to make a modification to this particular chunk of code: [JBrowse/View/FeatureGlyph/Gene.js#L68](https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/View/FeatureGlyph/Gene.js#L68-71), as follows:
```
var subRect = ( transcriptType.indexOf(subfeatures[i].get('type')) != -1:
                            ? this._ptGlyph()
                            : this._boxGlyph()
                          )._getFeatureRectangle( subArgs, subfeatures[i] );
````
And, adjust your track config as follows:
```
{
    ...
    transcriptType: "mRNA, ncRNA"
    ...
}
This will ensure that it will work with any of the feature types in the comma-separated list above.

**Please note**: this is a hack to the code for a quick fix. But it can be made more elegant by allowing the `transcriptType` config variable to be an array/list of feature types like: `["mRNA", "ncRNA", ...]`, much like the `subParts` config variable.

Hope this helps!

**Comment by vivekkrish** [comment]
The short answer is, no, it is currently not possible (without modifying some JBrowse code) to support 2 types of hierarchies in one *CanvasFeatures* track.

**Comment by ernestopicardi** [comment]
Many thanks. I found another workaround replacing "mRNA" and "ncRNA" with "transcript" in the original gff3. Then I included "exon" in subParts and added a callback function for color:

`"transcriptType": "transcript",
"subParts": "CDS, exon, five_prime_UTR, three_prime_UTR",
"style" : {
            "className" : "feature",
            "color" : "function(feature) { if (feature.get('type')=='exon') {return '#E32A3A';} else return '#2A3AE3';}"
         }
`
It seems to work.

**Comment by vivekkrish** [comment]
That's a good alternative fix! Glad you were able to resolve it. 👍

**Comment by cmdcolin** [comment]
Super! Sometimes just loading coding and non-coding as separate tracks helps too, but this is a good solution. Since the solution is config only, maybe we can close :)

**Comment by badilla** [comment]
hello @cmdcolin 
it would be nice to get the Gene.js code upgraded to dynamically read the transcriptType from the item to plot.
I have now applied the same workaround as @ernestopicardi and I confess I do not like to change the input data.
