### ISSUE TITLE
Doubt in Jbrowse

### ISSUE THREAD

**Issue by viv3kanand** [GMOD/jbrowse#779]
I am stuck at somepoint when I try to map a bam file over a genome. Will explain the steps I have followed. Please correct me if I was wrong or suggest any further steps needed.

1. Prepared fasta files using
 `bin/prepare-refseqs.pl --fasta hg19.fa` 
  and stored the data directory in root directory of Jbrowse

2. `add-bam-track.pl --label iclip --bam_url iclip.bam --in trackList.json`
   bam file and bed file are stored inside **data** directory

I could see **Genome** file but not the **bam** file I needed to map to the **genome**. I canview the **iclip label** in the browser though. I am not sure if these 2 steps are fair enough for jbrowser to visualize it. Any help is appreciated. Thank you.

**Comment by cmdcolin** [comment]
Is this a duplicate of #776? I am not sure what the problem is in this case.

That should be enough to visualize it.

For example I can even use the screenshot you have from #776, convert it to a BAM via OCR, and it visualizes fine.

![screenshot-localhost 2016-07-06 09-20-45](https://cloud.githubusercontent.com/assets/6511937/16621201/085ab37c-435b-11e6-8e7a-0a199d89d32f.png)

**Comment by viv3kanand** [comment]
It worked for me finally. It was just a path issue it seems. Thank you for the concern though. I will mark it closed.
