### ISSUE TITLE
flatfile-to-json.pl and GTF

### ISSUE THREAD

**Issue by Carlbioinfo** [GMOD/jbrowse#794]
Using flatfile-to-json.pl to add GTF (GFF3 to GTF with gffread software) doesn't show hat between introns , but adding the same file through Track > Open track file or URL shows the hat.

**Comment by vivekkrish** [comment]
Hi @Carlbioinfo ,

I believe this is mainly due to the fact that the `flatfile-to-json.pl` script officially does not support GTF format (but is still able to parse and load, since it is *like* GFF).

On the other hand, it works well via the **Track > Open track file** functionality because there exists, on the JBrowse client side, a javascript-based GTF parser that can handle this particular filetype.

Hope this helps!

Thank you.

**Comment by cmdcolin** [comment]
I'd just double what @vivekkrish says. The flatfile-to-json does not support GTF basically. You mentioned converting gff3 to gtf for use in flatfile-to-json, but i'd just use the gff3 originally.

**Comment by cmdcolin** [comment]
If no other issues I think we can close :)

jbrowse FAQ has a suggestion for GTF to GFF just in case you need to perform that http://gmod.org/wiki/JBrowse_FAQ#How_do_I_convert_GTF_to_GFF

**Comment by Carlbioinfo** [comment]
Thanks! At the end, it worked by converting to GFF  :)
