### ISSUE TITLE
Error in the Track File

### ISSUE THREAD

**Issue by Carlbioinfo** [GMOD/jbrowse#810]
Hi! 

I found that when the browser is on a region without associated feature in the track shows the following error: 

![erro_jbrowser](https://cloud.githubusercontent.com/assets/4893240/18546403/13ff2e2c-7b3e-11e6-86e6-dccff20d6767.png)

Is it right ? and Do you known how to deactivated this function ? 

Thanks!

**Comment by cmdcolin** [comment]
This is a guess, but maybe the server is not sending a proper 404 response for those regions without associated features. What server are you using?

**Comment by Carlbioinfo** [comment]
I am using nginx . What's kind of response should it be ? 
Thanks!

**Comment by Carlbioinfo** [comment]
I also see this in the web browser console (It might help) 

    .cache["dojo/request/handlers"]/</c.json@http://test/browser/src/dojo/dojo.js:386:149
    f@http://test/browser/src/dojo/dojo.js:385:10
    e@http://test/browser/src/dojo/dojo.js:379:121
    d@http://test/browser/src/dojo/dojo.js:382:225
    SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    Stack trace:
    .cache["dojo/request/handlers"]/</c.json@http://test/browser/src/dojo/dojo.js:386:149
    f@http://test/browser/src/dojo/dojo.js:385:10
    e@http://test/browser/src/dojo/dojo.js:379:121
    d@http://test/browser/src/dojo/dojo.js:382:225

Thks

**Comment by cmdcolin** [comment]
Thanks for checking those error console messages. It's hard to interpret as it is not using the "-dev" version from the downloads page, but you could try checking the "network" tab of your web browser console too. For example, see if requests to files like trackData.json are returning a 404 status code (because like you said, these areas should be empty)

If they are not returning a 404 status code, and maybe instead returns some other content like a default html page, then that won't parse as json and give an error like that

**Comment by Carlbioinfo** [comment]
Fixed. :)  Thanks @cmdcolin !

**Comment by cmdcolin** [comment]
Super. Glad that helped
