### ISSUE TITLE
BAM file unable to fetch

### ISSUE THREAD

**Issue by wanghuiyuan** [GMOD/jbrowse#825]
Hi there,
    I'm trying to visualise bam file but am hitting an error:  unable to fetch my.bam file. The file exists and I've placed in the ./data. 
    Any help much appreciated,

**Comment by cmdcolin** [comment]
You might also make sure that the bam file is indexed, because the bai file is what is fetched first

**Comment by wanghuiyuan** [comment]
Thanks for your reply. I have used samtools index before.

**Comment by cmdcolin** [comment]
Sounds good. If you can try and provide more details it will be easier to help though. If you can provide such things as a screenshot, tracklist.json contents, directory listing of data folder, web server used, jbrowse version, etc.

**Comment by colindaven** [comment]
I have had this error only when I mess the paths up, or when paths are changed in the file system. Sometimes it is also necessary to recreate the .bai if it is corrupted or moved.

**Comment by wanghuiyuan** [comment]
My bam file is in the data folder the same as tracks.conf. Screenshot and tracks.conf are in the attachment. The url is http://bioinfor.org/bioinfor/Jbrowse/ptr/?loc=NC_008467.2%3A23848201..23986700&tracks=ptr%2Cmy-bam-track%2CDNA&highlight=
[tracks.conf.txt](https://github.com/GMOD/jbrowse/files/558344/tracks.conf.txt)

**Comment by cmdcolin** [comment]
Looks like the permission s need fixing on the file. Visiting this gives 403 http://bioinfor.org/bioinfor/Jbrowse/ptr/data/SRR073115.bam

**Comment by wanghuiyuan** [comment]
thanks for your reply. This is the permissions of my bam file.
-rwxr-xr-x    1 bioinfo3 bioinfo3 304M 10月 28 06:17 SRR073115.bam*
-rwxr-xr-x    1 bioinfo3 bioinfo3 304M 10月 28 06:21 SRR073115.sorted.bam*
-rwxr-xr-x    1 bioinfo3 bioinfo3 888K 10月 28 06:24 SRR073115.sorted.bam.bai*

**Comment by cmdcolin** [comment]
It seems the BAM file is being gzipped by the server which causes errors for bam files.

For example, if I download the BAM file from your server, and manually gzip it on the command line, then it gives the same network response as if it was downloaded from your server.

The chrome error is the same too, net::ERR_CONTENT_DECODING_FAILED

I would disable mod_deflate or mod_gzip or whatever module is doing the gzipping on the server (or at least disable it for application/octet-stream type files which is what the BAM file mime type is given)


Gzip issues are always annoying to solve, but in this case it seems clear that it is being erroneously compressed with gzip and this gets handled wrong.

**Comment by cmdcolin** [comment]
Note: One way this could be handled on the jbrowse side is to not send Accept-Encoding: gzip on requests for bam files

**Comment by cmdcolin** [comment]
It is not actually possible to modify Accept-Encoding: gzip http://stackoverflow.com/questions/22362169/why-does-the-xmlhttprequest-spec-prevent-setting-the-accept-encoding-header

I guess in the best case we can only try and fix the misbehaving server setup that you have @wanghuiyuan  but since this isn't really a jbrowse problem, I might suggest closing.

Feel free to add comments anyways


Notes:

Red circle refers to bam file coming from remote server and the track does NOT work, with Content-Encoding: gzip set (which I think is causing the issue)

Uncircled screenshot refers to bam file coming from local apache and the track DOES work without any customizations and it does not have Content-Encoding: gzip 

![2016-11-03-091344_1280x800_scrot](https://cloud.githubusercontent.com/assets/6511937/24205979/4b8273e2-0ef3-11e7-92a1-5974ffc3feed.png)
![2016-11-03-091311_1280x800_scrot](https://cloud.githubusercontent.com/assets/6511937/24205978/4b819fc6-0ef3-11e7-8bfa-8586f4471e1f.png)
