### ISSUE TITLE
CanvasFeature removes Features

### ISSUE THREAD

**Issue by LuisSoares** [GMOD/jbrowse#888]
When a maximum height is reached, the offending Features are removed from the track, This causes both parent and subfeatures to not be displayed when the maximum height is reached.

**Comment by cmdcolin** [comment]
Typically what CanvasFeatures does it has a maxHeight, and if the number of features can't be contained in maxHeight, then it says Max height exceeded

![screenshot-jbrowse org-2017-05-03-16-19-36](https://cloud.githubusercontent.com/assets/6511937/25679739/5f163994-301c-11e7-958c-1892e7aa773a.png)


Is this what you are seeing? You can add "maxHeight": 1200 or something to your config file to try to remedy. The default is 600 I believe

**Comment by LuisSoares** [comment]
My problem is that maxheight is not just truncating it is removing all related features.
Eg:
I am plotting the same track with HTML features (top) and Canvas features (bottom). If you notice there is a row of features in the middle absent from the canvas features
![jbrowse1](https://cloud.githubusercontent.com/assets/7463255/25680525/2462e682-301f-11e7-8c93-9e08544d3acd.png)

The features are there since the are shown if compact view is selected:
![jbrowse2](https://cloud.githubusercontent.com/assets/7463255/25680554/3f684ad0-301f-11e7-827d-c6ebd100f0db.png)

**Comment by cmdcolin** [comment]
In the CanvasFeatures case, it treats the group of transcripts as a gene glyph, it won't display a partial part of the gene glyph, so since it is too big it just doesn't plot it at all and shows the max height exceeded warning.

Technically you could load the CanvasFeatures track at the transcript level too (e.g. add --type mRNA and --trackType CanvasFeatures to flatfile-to-json.pl) and it would probably look a lot like the htmlfeatures track

**Comment by LuisSoares** [comment]
Cool, that works. Thanks
