### ISSUE TITLE
Problem exporting with 'Save track data'

### ISSUE THREAD

**Issue by caguirred** [GMOD/jbrowse#894]
Hi,
When I try to export 'Highlighted region' or 'Visible region' from track other than "Reference sequence", I always obtain full feature (BED, GFF3), not just selected region. When i try with "Reference sequence" only can export fasta data, but i want a BED file for selected region. Is there any option to export a BED file from 'Highlighted region' from reference sequence? A button for to export BED format region (e.g. Highlighted) from tracks would be very usefull.

**Comment by colindaven** [comment]
Why not just zoom into the exact coordinates of the highlighted region and select Save - > Visible region ?

**Comment by caguirred** [comment]
Hi
This aproach does not work. It always returns full feature cordinates, not just selected (highlighted) region and exporting from reference sequence track, you only obtain the FASTA (not BED).

**Comment by colindaven** [comment]
Hi,
To get BED data you need to export from a BED track. The reference sequence track only contains sequence. 
My users and me have always been very happy with the zoom to region and then export. We primarily use GFF3 but BED works fine too.

**Comment by caguirred** [comment]
Hi,
Maybe I didn't explain very well (sorry). For example, suppose you have a visible region of Chr01 from 20.000.000 to 20.010.000 and a highlighted region form 20.000.100 to 20.000.600. When you select save track data from reference sequence, in the pop-up window apear "Region to save": 
Highlighted: Chr01:20.000.100..20.000.600 (500 b)
Visible: Chr01:20.000.000..20.010.000 (10000 pb)

I need an option to view in the 'Tab spaced' format: Chr1      20000100      20000600      TEST1      +
It's because I need this data for use it in another program.

Thanks for your time

**Comment by cmdcolin** [comment]
Is there some special case where you are seeing a bug? It seems to work otherwise

For example, visiting a track on the sample browser, highlighting a small region, will only export the selected features 

![screenshot-jbrowse org-2017-05-31-13-43-23](https://cloud.githubusercontent.com/assets/6511937/26645727/25f22ece-4607-11e7-8410-9bf5d7f63aa9.png)

**Comment by cmdcolin** [comment]
Note that when the region is highlighted, you get the export highlighted region option in the "Save track data" dialog box

![screenshot-jbrowse org-2017-05-31-13-44-16](https://cloud.githubusercontent.com/assets/6511937/26645763/4e9d27ac-4607-11e7-8b13-478c3dbb5545.png)

**Comment by colindaven** [comment]
Hi @cmdcolin 
I think @caguirred  wants to extract BED format coordinates (and not the sequence) from the highlighted section when clicking on the Save data from the the _reference sequence_ track. 

I have tried to explain BED format coordinates are only picked up from an existing feature track with BED GFF3 or similar features. I guess the coordinates of the highlighted region could be picked out of the URL fairly easily though.

It might be worthwhile to offer an option (i.e. in the top menu - view/save highlighted coordinates). It doesn't seem to me that this request fits to any existing tracks though, since the highlight is user-defined.

**Comment by cmdcolin** [comment]
Oh gotcha. that makes more sense. kind of reminds me of a "bookmark saving" approach (maybe even this plugin https://github.com/awilkey/bookmarks-jbrowse)
