### ISSUE TITLE
Alignments2 - Mate/next location

### ISSUE THREAD

**Issue by keiranmraine** [GMOD/jbrowse#907]
The options to quick view or open in a new tab render the marker (orange line) 1bp to the left of the actual coordinate:

Link from here:
![screen shot 2017-07-14 at 15 42 24](https://user-images.githubusercontent.com/3740323/28216905-29a9e4dc-68ab-11e7-9ec0-48e7eb082d54.png)

To here:
![screen shot 2017-07-14 at 15 43 00](https://user-images.githubusercontent.com/3740323/28216913-327a4566-68ab-11e7-9d15-932ab516fad0.png)

**Comment by rbuels** [comment]
Think you can investigate this one @rdhayes ?

**Comment by rdhayes** [comment]
I see this in the sample data, sure. I have a full plate today, but can take a look tomorrow or early next week.

**Comment by rdhayes** [comment]
Is there more test data than the same_data Volvox "BAM - paired end test pattern at 28kb)" track? I am tempted to think the fix is not so simple, but I see highlighting of the correct base if I simply add 1 to the integer read from the BAM in Store/SeqFeature/BAM/LazyFeature.js function _next_pos(), as currently returned by line 262.

**Comment by keiranmraine** [comment]
Sure, you can use this:

ftp://ngs.sanger.ac.uk/production/cancer/dockstore/cgpwgs/

Corresponding ref in here:

ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/human/core_ref_GRCh37d5.tar.gz

**Comment by rdhayes** [comment]
Your BAM is too big to download efficiently. Could you provide just chromosome 1 or even smaller slice? 

Part of this is the highlight of the start of mate pairs as a sharp line at the start coordinate, rather than a highlight of the full start coordinate column. Using the Volvox "proper_f_r" example, the location string returned by feature.get('next_segment_position') is the correct interbase ctgA:28135, but this is ultimately translated by Util.parseLocString() and assembleLocString to "ctgA:28135..28134". I think what we want is "ctgA:28136..28135" to highlight start of the correct base. The format looks odd, but is what gives us the current "interbase" highlight. 

Question 1: is Util.parseLocString with a single coordinate performing as we expect here? It is parsing "ctgA:28135" to an object with start=28134 and end=28134 (Util.js line 314). I am wondering why one is subtracted (should be start=28135, end=28135?)

Question 2: For Alignments2.js next/previous mate highlighting, I have a working fix that is a rewrite of feature.get('next_segment_position') to return strings of the correct line highlight format (like "ctgA:28136..28135"). 

What are other use cases for feature.get('next_segment_position') from BAM files? I don't wish to break anything expecting the single interbase start coordinate, though I don't see this attribute used elsewhere in the main codebase. Another option would be to add another getter function called 'next_segment_position_highlight' and update Alignments2 to use that instead in this instance.

Thoughts?

**Comment by keiranmraine** [comment]
There's a far smaller dataset covering a small region on 21 here:

ftp://ngs.sanger.ac.uk/production/cancer/dockstore/cgpwxs/
