### ISSUE TITLE
How to add customize information in details popup

### ISSUE THREAD

**Issue by zch0803** [GMOD/jbrowse#950]
I don't know how to add some customize information in my details popup. After running flatfile_to_json.pl for bed file, Jbrowse would load basic information in details popup. I have searched in Gmod wiki, but I didn't find any instructions. And today, Gmod wiki server is down. So are there any suggestions? Thanks very much.

**Comment by enuggetry** [comment]
This was answered by @scottcain in gmod-ajax

The details display you see there is JBrowse "regurgitating" everything it knows about a feature.  That information comes from the GFF file that gets loaded.  Items that aren't specified somewhere else (like the chromosome coordinates, strand and score) all come from the the ninth column of the GFF via "tag=value" entries separated by semicolons.  GFF lets you add anything you want there, as long as it adhears to the GFF3 specification (https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md, see Column 9: "attributes").  Note that JBrowse capitalizes that first character of each tag, so that in your figure 2 example, it has "Repclass: SINE" but the GFF presumably had "repclass=SINE" in column nine.

Also note that once you get the hang of "simple" JBrowse, there is a lot more you can do.  For example, at WormBase, I have several tracks where I provide mouseover activated popups where the information is presented without having to even click.  See for example http://www.wormbase.org/tools/genome/jbrowse-simple/?data=data%2Fc_elegans_PRJNA13758&loc=III%3A13448981..13449909&tracks=Million%20Mutation%20Project and mouseover some of the features.
